### ISSUE TITLE
Market app cannot access public marketplace from container.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud-docker/server#10]
### Steps to reproduce

1. Go to market app

### Expected behaviour

Market can be used to install apps.

### Actual behaviour

There are errors.

![screen shot 2017-05-23 at 14 04 17](https://cloud.githubusercontent.com/assets/9048796/26353656/b8445dca-3fc1-11e7-97f8-6e7c5feb1864.png)

### Docker image tag
10.0.1

**Updated from an older ownCloud or fresh install:**
Fresh

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

**Logs**

```
```

### Client configuration

**browser**
Firefox

**Comment by tboerger** [comment]
Where does `/mnt/data/files/files_external/rootcerts.crt` come from? That sounds like you are configuring custom certificates, so it's out of the scope of the Docker container.

**Comment by SergioBertolinSG** [comment]
I didn't set up any certificates, this is just using the docker image, not extra configuration.

**Comment by tboerger** [comment]
But where does `/mnt/data/files/files_external/rootcerts.crt` come from? I can not see this error on any installation with the public marketplace.

**Comment by SergioBertolinSG** [comment]
No idea, that folder /mnt/data is included in the docker container as a volume and it is using it as the oc data folder.

**Comment by felixboehm** [comment]
removing the cert, which should not be there, solved the marketplace access.
Please try again with fresh setup, reopen if reproducible.

**Comment by SergioBertolinSG** [comment]
Worked as expected. There were previous docker volumes messing the environment.
