### ISSUE TITLE
Upgrade error because of utf8mb4 charset change

### ISSUE THREAD

**Issue by ThomDietrich** [owncloud-docker/server#102]
Hello, I'm following up on the closed issue https://github.com/owncloud-docker/server/issues/39 and https://github.com/owncloud/core/issues/30174

The reported error is still valid. I want to upgrade my setup to the latest owncloud version but that is not possible due to the `utf8mb4` switch. Could you advice me on how to fix the issue? If other users might be effected, a migration automation should be implemented I guess.

Thanks for your help!

```
$ sudo docker-compose exec owncloud occ upgrade
ownCloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
2018-01-17T12:39:20+00:00 Set log level to debug
2018-01-17T12:39:20+00:00 Repair step: Repair MySQL database engine
2018-01-17T12:39:20+00:00 Repair step: Repair MySQL collation
2018-01-17T12:39:20+00:00 Repair info: Change collation for oc_accounts ...
2018-01-17T12:39:20+00:00 Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'ALTER TABLE `oc_accounts` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;':

SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes
2018-01-17T12:39:20+00:00 Update failed
2018-01-17T12:39:20+00:00 Maintenance mode is kept active
2018-01-17T12:39:20+00:00 Reset log level
```

**Comment by tboerger** [comment]
What about removing the utf8mb4 env variable again? Have you tried that?

**Comment by ThomDietrich** [comment]
Yes I did (last time it worked). This time it didn't work, probably because of all the other changes to the image.
Generally I was anyhow not satisfied with this solution. The offered docker container should take care of those migration steps. Not primarily for me but for other users.

This is the scary part about dockerization. You relief yourself from the administration of a complex (linux) system by utilization of separated docker containers. However at the same time you loose control (i.e. practical setup experience) and rely on the docker project to offer concise increments of the application. Long story short, I'd like to encourage you to work with me to find a solution that can then be implemented in the container.

My system is fully backuped (more precisely snapshotted) and I am ready to test steps and a new image.

**Comment by tboerger** [comment]
I personally don't have experience with the utf8mb4 internals of ownCloud. I know there is some task to convert to utf8mb4, but I never tried it.

Maybe somebody like @patrickjahns or @DeepDiver1975 can help on that.

Besides that, the offered docker-compose.yml is just a reference how somebody could deploy it easily. It's not meant as a full blown deployment that never got breaking changes. Maybe it's better to drop these docker-compose.yml sample entirely from the repository.
