### ISSUE TITLE
Error while trying to create admin user

### ISSUE THREAD

**Issue by reztarter** [owncloud-docker/server#105]
When I run docker-compose up -d one container (owncloud) is in Restarting state:
`# docker-compose ps`
`     Name                   Command                 State             Ports`
`----------------------------------------------------------------------------------`
`neu_db_1         docker-entrypoint.sh mysqld      Up           3306/tcp, 33060/tcp `
`neu_owncloud_1   /usr/bin/entrypoint /usr/b ...   Restarting`                       
`neu_redis_1      /usr/bin/entrypoint /bin/s ...   Up           6379/tcp`

In owncloud's log:
`# docker-compose logs owncloud`
`owncloud_1  | Creating volume folders...`
`owncloud_1  | Creating hook folders...`
`owncloud_1  | Waiting for MySQL...`
`owncloud_1  | wait-for-it: waiting 180 seconds for db:3306`
`owncloud_1  | wait-for-it: db:3306 is available after 0 seconds`
`owncloud_1  | Waiting for Redis...`
`owncloud_1  | wait-for-it: waiting 60 seconds for redis:6379`
`owncloud_1  | wait-for-it: redis:6379 is available after 0 seconds`
`owncloud_1  | Writing config file...`
`owncloud_1  | Fixing base perms...`
`owncloud_1  | Fixing data perms...`
`owncloud_1  | Fixing hook perms...`
`owncloud_1  | Installing server database...`
`owncloud_1  | Error while trying to create admin user: Failed to connect to the database: An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'owncloud'@'172.20.0.4' (using password: YES)`
`owncloud_1  |  -> `

But when I created user owncloud in mysql container:
`# docker-compose exec db bash`

`mysql> CREATE USER 'owncloud'@'localhost' IDENTIFIED BY 'password';`

`mysql> CREATE USER 'owncloud'@'172.20.0.4' IDENTIFIED BY 'password';`

`mysql> GRANT ALL PRIVILEGES ON owncloud.* TO 'owncloud'@'localhost';`

`mysql> GRANT ALL PRIVILEGES ON owncloud.* TO 'owncloud'@'172.20.0.4';`

`mysql> FLUSH PRIVILEGES;`

and then run
`# docker-compose stop`
`# docker-compose down`
`# docker-compose up -d`

Situation is not changed - owncloud container is still in Restarting state and in owncloud's log exists the same error message:
`owncloud_1  | Error while trying to create admin user: Failed to connect to the database: An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'owncloud'@'172.20.0.4' (using password: YES)`

**Comment by tboerger** [comment]
Also related to your other issue at https://github.com/owncloud-docker/server/issues/103
