### ISSUE TITLE
please support/document using sqlite as a mariadb alternative for the docker image

### ISSUE THREAD

**Issue by jmtd** [owncloud-docker/server#107]
I'm a happy user of the [docker-dot-com image](https://hub.docker.com/_/owncloud/) that is being sunset at the end of the year. (I imagine I'm not alone).

I am looking at and planning my migration from that image to the officially supported ones. (I'm sure there are plenty of others in this situation too, who might benefit from a migration guide) My owncloud deployment is very small (principally, one user, me) and sqlite (as the docker-dot-com image is configured to use by default) makes a lot of sense in my situation. Therefore I would prefer to continue to use it.

The documentation for the official image talks about requiring separate mariadb/mysql and redis containers. It would be great if it was both a) supported and b) documented to run the official container with sqlite, removing the need for a separate database container, and (if possible, I've no idea) the redis container too (which, would remove the need for container orchestration entirely)

**Comment by tboerger** [comment]
It's not documented because it's simply not recommended. It's possible to use sqlite since we are using it within the ci system and it's also possible to not use redis, but that slows down file locking massively.

**Comment by tboerger** [comment]
Since it's not recommended it won't be documented. You should migrate to a proper database.

**Comment by jmtd** [comment]
> Since it's not recommended it won't be documented. You should migrate to a proper database.

Thanks but it will prove easier to move to nextcloud (who *do* support this setup) than to run a full blown DBMS, the need for which is provably false, since the docker-dot-com owncloud images work have worked for me without one for over a year.

**Comment by tboerger** [comment]
ownCloud and also Nextcloud is displaying a warning within the admin interface, that's why it's preferred to use some real database for ownCloud. SQLite works with ownCloud, but it is simply not recommended. If you got the feeling it works better with Nextcloud (which is not the case) feel free to use Nextcloud.

> SQLite is used as database. For larger installations we recommend to switch to a different database backend.
> Especially when using the desktop client for file syncing the use of SQLite is discouraged.
> To migrate to another database use the command line tool: 'occ db:convert-type', or see the documentation ↗.
