### ISSUE TITLE
docker-compose up -d

### ISSUE THREAD

**Issue by 15565675103** [owncloud-docker/server#109]
owncloud_1_9e4e9a3f1827 | Creating volume folders...
owncloud_1_9e4e9a3f1827 | Creating hook folders...
owncloud_1_9e4e9a3f1827 | Waiting for MySQL...
owncloud_1_9e4e9a3f1827 | wait-for-it: waiting 180 seconds for db:3306
owncloud_1_9e4e9a3f1827 | wait-for-it: timeout occurred after waiting 180 seconds for db:3306

**Comment by tboerger** [comment]
Inspect your docker network, nothing where I can really help. The owncloud container is waiting for a successful ping to the mariadb Container.

**Comment by XorSum** [comment]
This project must run "docker-compose up -d" twice. At first , use "db:image: webhippie/mariadb:latest" , and second "db:image: mariadb:latest". I don't know why but it works.
