### ISSUE TITLE
Use the docker. IO/webhippie/mariadb mirror, start owncloud error

### ISSUE THREAD

**Issue by MRwangyd** [owncloud-docker/server#110]
Installing server database...
Error while trying to create admin user: An exception occurred while executing 'SELECT COLUMN_NAME AS Field, COLUMN_TYPE AS Type, IS_NULLABLE AS `Null`, COLUMN_KEY AS `Key`, COLUMN_DEFAULT AS `Default`, EXTRA AS Extra, COLUMN_COMMENT AS Comment, CHARACTER_SET_NAME AS CharacterSet, COLLATION_NAME AS Collation FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = 'owncloud' AND TABLE_NAME = 'oc_appconfig'':

SQLSTATE[HY000]: General error: 1036 Table '/tmp/#sql_ed_0.MAI' is read only

Use the docker. IO/webhippie/mariadb mirror, start owncloud error

Start the command as follows

docker run -d \
  --name mariadb \
  -e MARIADB_ROOT_PASSWORD=owncloud \
  -e MARIADB_USERNAME=owncloud \
  -e MARIADB_PASSWORD=owncloud \
  -e MARIADB_DATABASE=owncloud \
  --volume /mapbar/data/owncloud/data/mysql:/var/lib/mysql \
  --volume /mapbar/data/owncloud/data/mysql-back:/var/lib/backup \
  docker.io/webhippie/mariadb:latest

OWNCLOUD_DOMAIN=yp.mapbar.com
OWNCLOUD_ADMIN_USERNAME=ypadmin
OWNCLOUD_ADMIN_PASSWORD=111qqq,,,
OWNCLOUD_VERSION=10.0.8
HTTP_PORT=80
HTTPS_PORT=443
OWNCLOUDPATH=/mapbar/data/owncloud/data/owncloud

docker run -d \
  --name owncloud \
  --link mariadb:db \
  --link redis:redis \
  -p ${HTTP_PORT}:80 \
  -p ${HTTPS_PORT}:443 \
  -e OWNCLOUD_DOMAIN=${OWNCLOUD_DOMAIN} \
  -e OWNCLOUD_DB_TYPE=mysql \
  -e OWNCLOUD_DB_NAME=owncloud \
  -e OWNCLOUD_DB_USERNAME=owncloud \
  -e OWNCLOUD_DB_PASSWORD=owncloud \
  -e OWNCLOUD_DB_HOST=db \
  -e OWNCLOUD_ADMIN_USERNAME=${ADMIN_USERNAME} \
  -e OWNCLOUD_ADMIN_PASSWORD=${ADMIN_PASSWORD} \
  -e OWNCLOUD_REDIS_ENABLED=true \
  -e OWNCLOUD_REDIS_HOST=redis \
  --volume $OWNCLOUDPATH:/mnt/data \
  -v /mapbar/data/owncloud/data/autoai-sslkey:/mnt/data/certs \
  owncloud/server:${OWNCLOUD_VERSION}

**Comment by MRwangyd** [comment]
Use the docker. IO/webhippie/mariadb: latest starts, generate data directory.
Docker.io /mariadb: owncloud container can be started, but The username is already being used error appears when admin user is upgraded

**Comment by MRwangyd** [comment]
https://github.com/owncloud-docker/server/issues/38
The problem was reported in version 10.0.4

**Comment by MRwangyd** [comment]
![image](https://user-images.githubusercontent.com/27405334/50134108-8552f800-02c9-11e9-825b-9e4ea9fecde4.png)
The directory that maps out looks like this. Is that correct

**Comment by tboerger** [comment]
You are using an outdated version. Please upgrade.
