### ISSUE TITLE
Unable to access OC server via port 8080

### ISSUE THREAD

**Issue by sd1998** [owncloud-docker/server#111]
I followed the steps to setup OC server using docker-compose and started the container but I am unable to connect to the server via PORT 8080:-

<img width="1440" alt="screenshot 2018-12-21 at 6 00 10 pm" src="https://user-images.githubusercontent.com/22047421/50342795-978f9900-054a-11e9-8084-c54bd38eda12.png">
As you can see here the containers are running.
<img width="1117" alt="screenshot 2018-12-21 at 5 59 53 pm" src="https://user-images.githubusercontent.com/22047421/50342809-a37b5b00-054a-11e9-894d-a57fa7743272.png">

**Comment by tboerger** [comment]
The screenshot shows pretty clear the the host port is set to port 80, of course it won't work to access ownCloud via port 8080.

**Comment by sd1998** [comment]
@tboerger The case is the same with PORT 80

**Comment by tboerger** [comment]
Since it's correctly bound to port 80 and the container is marked as healthy the issue isn't really related to the docker image but somehow to your docker setup. That's really out of the scope where I can help.

**Comment by tboerger** [comment]
Maybe because it's listing the old container ports 80 and 443 I can only guess that you are running an old container pre 10.0.10
