### ISSUE TITLE
Can't etablish connection with Owncloud and Docker

### ISSUE THREAD

**Issue by chopin2712** [owncloud-docker/server#112]
I created a cloud with owncloud run in docker. I download and extract this :

https://github.com/owncloud-docker/server

I open terminal in the folder and I type this :

`sudo docker-compose up`

So when I go by 127.0.0.1 That work, when I go by 192.168.1.36 that works too.

I opened the ports 80 for 192.168.1.36 and I go by my public IP address. And firefox tell me :

"Unable to connect"

So I try by Chrome and it say :

xx.xxx.xx.xx refused to connect ERR_CONNECTION_REFUSED

I try to change the addresses in the document docker-compose.yml but nothing change.

Thanks in advance

Chopin

PS : I use Ubuntu 18.10 Desktop PS2 : I already try to stop docker and to start again but nothing change...

**Comment by tboerger** [comment]
Since it's working with your private ip there seems to be no issue with the owncloud container. I can't provide general docker support.

**Comment by chopin2712** [comment]
> Since it's working with your private ip there seems to be no issue with the owncloud container. I can't provide general docker support.

Yes but I test and that give me the same problem for all docker apps, like Wordpress and more.

**Comment by tboerger** [comment]
Yeah, not an issue with our container ;)
