### ISSUE TITLE
Unknown error "error" uploading file "file"

### ISSUE THREAD

**Issue by TooFiveFive** [owncloud-docker/server#113]
I'm after setting up my owncloud server and have an issue where I get that error message above when I upload a file more than 2mb. I tried changing the php.ini and setting the env var but nothing's working.

**Comment by boardfish** [comment]
I'm also having this issue. I'm hosting my OwnCloud behind nginx-proxy, and changing the proxy config there isn't doing anything.

**Comment by tboerger** [comment]
The owncloud docker image accepts files bigger than 2mb, so it's not an issue with this image.

**Comment by boardfish** [comment]
I already get the sense that it's something to do with my setup - the container (running Apache) is behind an NGINX proxy, so there's bound to be a bottleneck somewhere. Do you know the maximum filesize that the image accepts? I'm testing with a data export that clocks in at about 3GB.

**Comment by boardfish** [comment]
I don't remember the exact details, but last night I think I circumvented this issue by adding this to `.htaccess` inside the container:

```
<IfModule mod_php5.c>
php_value upload_max_filesize = 16G 
php_value post_max_size = 16G
</IfModule>
```

**Comment by boardfish** [comment]
However, I'm still very much at the mercy of what seems to be a bandwidth limit - investigating.

**Comment by tboerger** [comment]
The max upload size is set to 20g at https://github.com/owncloud-docker/base/blob/master/README.md#available-environment-variable, but this limit won't be reached because owncloud chunks the uploads.

**Comment by boardfish** [comment]
The limits were enforced by the NGINX proxy I had in the way. I've been meaning to document how I've configured it for my own sake, so I'll sum it up and reply here.

**Comment by ericm** [comment]
Same here. Just increase your upload limits in your reverse proxy config.
