### ISSUE TITLE
Performing a DB dump/backup

### ISSUE THREAD

**Issue by mauriceelagu** [owncloud-docker/server#114]
I have installed **ownCloud** on my local machine using **Docker (docker-compose)**
I however have a few queries since the application is new to me especially regards backups or recovery

 How can I perform a database dump on my database image**(owncloud-docker-server_db_1)**?

**Comment by tboerger** [comment]
If you are using the MariaDB image used within the reference docker-compose.yml there is a cronjob executed every night within the MariaDB container, but you can always enforce a backup with `docker-compose exec db backup`, this will place a backup within a volume used by the db container. Within the container the path is `/var/lib/backup/backup.X`, while X gets rotated on every backup from 1 till 14. You can see the available backups with `docker-compose exec db ls /var/lib/backup/*`.
