### ISSUE TITLE
latest tag is owncloud 10.0.9

### ISSUE THREAD

**Issue by individual-it** [owncloud-docker/server#115]
it looks for me like `:latest` is still on 10.0.9

starting `OWNCLOUD_RELEASE_DOCKER_TAG=10.0.10 docker-compose  -f owncloud-base.yml -f owncloud-official.yml  -f database/postgres.yml up` gives me oC 10.0.10 but
` OWNCLOUD_RELEASE_DOCKER_TAG=latest docker-compose  -f owncloud-base.yml -f owncloud-official.yml  -f database/postgres.yml up` gives me 10.0.9

**Comment by tboerger** [comment]
You should execute `OWNCLOUD_RELEASE_DOCKER_TAG=latest docker-compose -f owncloud-base.yml -f owncloud-official.yml -f database/postgres.yml pull` first, that would show you that you latest image was just outdated.
