### ISSUE TITLE
Access denied for user 'owncloud'

### ISSUE THREAD

**Issue by daAftermath** [owncloud-docker/server#117]
this is my docker-compose.yml

    version: '2.1'

    volumes:
        files:
            driver: local
        mysql:
            driver: local
        backup:
            driver: local
        redis:
            driver: local

    services:
        owncloud:
            image: owncloud/server:latest
            restart: always
            ports:
            - 8585:8080
        depends_on:
            - db
            - redis
        environment:
            - OWNCLOUD_DOMAIN= localhost
            - OWNCLOUD_DB_TYPE= mysql
            - OWNCLOUD_DB_NAME= owncloud
            - OWNCLOUD_DB_USERNAME= owncloud
            - OWNCLOUD_DB_PASSWORD= owncloud
            - OWNCLOUD_DB_HOST= db
            - OWNCLOUD_ADMIN_USERNAME= admin
            - OWNCLOUD_ADMIN_PASSWORD= admin
            - OWNCLOUD_MYSQL_UTF8MB4= true
            - OWNCLOUD_REDIS_HOST= redis
        healthcheck:
            test: ["CMD", "/usr/bin/healthcheck"]
            interval: 30s
            timeout: 10s
            retries: 5
        volumes:
            - files:/mnt/data

    db:
        image: mariadb:latest
        restart: always
        environment:
            - MARIADB_ROOT_PASSWORD= owncloud
            - MARIADB_USERNAME= owncloud
            - MARIADB_PASSWORD= owncloud
            - MARIADB_DATABASE= owncloud
            - MARIADB_MAX_ALLOWED_PACKET= 128M
            - MARIADB_INNODB_LOG_FILE_SIZE= 64M
        healthcheck:
            test: ["CMD", "/usr/bin/healthcheck"]
            interval: 30s
            timeout: 10s
            retries: 5
        volumes:
            - mysql:/var/lib/mysql
            - backup:/var/lib/backup

    redis:
        image: redis:latest
        restart: always
        environment:
            - REDIS_DATABASES=1
        healthcheck:
            test: ["CMD", "/usr/bin/healthcheck"]
            interval: 30s
            timeout: 10s
            retries: 5
        volumes:
            - redis:/var/lib/redis`

and this the error i am getting if running with `docker-compose up`
![err](https://user-images.githubusercontent.com/44099426/54101645-f3b3cd80-4381-11e9-953f-c298194ae6e5.PNG)

container keeps on restarting if running with `docker-compose up -d`
![aa](https://user-images.githubusercontent.com/44099426/54101674-134af600-4382-11e9-8d04-ee576b3c0653.PNG)

i am running linux containers on windows
this is my server computer so it also runs mysql server on port 3306.

**Comment by tboerger** [comment]
You can see at https://hub.docker.com/_/mariadb#environment-variables that the MariaDB container is using `MYSQL_` environment variable prefixes. If you fix that I'm pretty sure it will work.

**Comment by daAftermath** [comment]
From the documentation link what i understand is that prfixes `MARIADB_` needs to be replaced by `MYSQL_`
I have changed these 4 lines
              `  - MYSQL_ROOT_PASSWORD= owncloud`
               `- MYSQL_USER= owncloud`
                `- MYSQL_PASSWORD= owncloud`
             `   - MYSQL_DATABASE= owncloud`
but still the result is same. i don't know what i am doing wrong
I am actually new to whole docker containers thing.
can you please elaborate a little bit.
thanks

**Comment by daAftermath** [comment]
> You can see at https://hub.docker.com/_/mariadb#environment-variables that the MariaDB container is using `MYSQL_` environment variable prefixes. If you fix that I'm pretty sure it will work.

From the documentation link what i understand is that prfixes `MARIADB_` needs to be replaced by `MYSQL_`
I have changed these 4 lines
              `  - MYSQL_ROOT_PASSWORD= owncloud`
               `- MYSQL_USER= owncloud`
                `- MYSQL_PASSWORD= owncloud`
             `   - MYSQL_DATABASE= owncloud`
but still the result is same. i don't know what i am doing wrong
I am actually new to whole docker containers thing.
can you please elaborate a little bit.
thanks

**Comment by tboerger** [comment]
I'm not able to give basic Docker support, this issue is not related to ownCloud, feel free to contact the maintainers of the MariaDB docker container if you are not able to connect to the database.

**Comment by daAftermath** [comment]
Is there any way i can connect it to the MYSQL server that i have in my machine.

**Comment by tboerger** [comment]
> Is there any way i can connect it to the MYSQL server that i have in my machine.

Only via your public IP address. Host ports can't get connected into a container.

**Comment by daAftermath** [comment]
I switched MARIADB to
       ` image: webhippie/mariadb:latest`
and changed the environment variables using https://github.com/dockhippie/mariadb to
`- MARIADB_ROOT_PASSWORD= owncloud`
   `         - MARIADB_USER= owncloud`
    `        - MARIADB_PASSWORD= owncloud`
     `       - MARIADB_DATABASE= owncloud`
      `      - MARIADB_MAX_ALLOWED_PACKET= 128M`
       `     - MARIADB_INNODB_LOG_FILE_SIZE= 64M`

this is my error now
`Error while trying to create admin user: Failed to connect to the database: An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'owncloud'@'docker_owncloud_1.docker_default' (using password: YES)`
![err](https://user-images.githubusercontent.com/44099426/54131055-ce997c00-43ce-11e9-8eca-8d4ab39f5e9e.PNG)

**Comment by tboerger** [comment]
Since this error happens with both MariaDB images this sounds like a network issue on your server.
