### ISSUE TITLE
How to connect to external database

### ISSUE THREAD

**Issue by jasam30011** [owncloud-docker/server#118]
i have a server machine which runs database engines and has a public ip address. can i connect docker container to that server and use its database as i have a similar problem to this gentleman https://github.com/owncloud-docker/server/issues/117#issue-419297068

i have tried many things and have been onto it from 8 days now.

thanks

**Comment by tboerger** [comment]
Just check the environment variables at https://github.com/owncloud-docker/base/blob/master/README.md#available-environment-variable, set the OWNCLOUD_DB_* variables to connect to your database.
