### ISSUE TITLE
Sharing links with https:// not http://

### ISSUE THREAD

**Issue by crackhd** [owncloud-docker/server#119]
A brief search over issues did not show any solution.

When i share links, they are `http://`. This is because i often browse ownCloud via address like `http://192.168.0.1`, but i have a public reverse proxy with domain and TLS termination

Users must have an option to force `https://` and custom domain in shared links.

**Comment by tboerger** [comment]
This is not a feature related to the docker image, but you should ask for such a feature upstream in the core repo.

**Comment by crackhd** [comment]
This is a configuration question, this feature must be present already, just undocumented
