### ISSUE TITLE
Update SSL information in README.md

### ISSUE THREAD

**Issue by michaelstingl** [owncloud-docker/server#122]
@tboerger I heard this is no longer valid:

https://github.com/owncloud-docker/server/blob/ad25c2c5cb7d96bdacb40013de4bbcaa467f8578/README.md#L164-L171

What is the "official" recommendation to setup SSL? Link to docs?
(small setup for testing in my case)

**Comment by tboerger** [comment]
I want to remove the whole "documentation" part from the readme. I want to link to the ownCloud docs instead.

**Comment by michaelstingl** [comment]
> I want to link to the ownCloud docs instead.

👍

**Comment by marcelopasin** [comment]
What about removing mentions to https and port 443 in the README.md? They are misleading. I spent hours searching for it, only to find out that SSL is not enabled at all in your container image.

**Comment by omegahelix77** [comment]
I agree this is incorrect and misleading. For those who want to know, here is what you can do to enable SSL in the owncloud docker image (using docker-compose):

1. Start up the container
2. Log into the container, move apache2 config to permanent storage
    a. docker exec <image hash> bash
    b. cp -a /etc/apache2 /mnt/data
    c. mv /etc/apache2 /etc/apache2.orig
    d. ln -s /mnt/data/apache2 /etc/apache2
    e. exit
3. Save modified docker image
   a. docker commit <hash> owncloud_custom
4. docker-compose down
5. Enable ssl, etc mods for apache
    a. cd /var/lib/docker/volumes/owncloud_files/_data/apache2/mods-enabled
    b. ln -s ../mods-available/ssl.conf; ln -s ../mods-available/ssl.load; ln -s ../mods-available/socache_shmcb.load
    c. Create SSL configuration file for apache at /var/lib/docker/volumes/owncloud_files/_data/apache2/sites-enabled/default-ssl.conf:

> LoadModule ssl_module modules/mod_ssl.so
> 
> Listen 443
> <VirtualHost *:443>
>   SSLEngine on
>   SSLCertificateFile "/mnt/data/your_cert.crt"
>   SSLCertificateKeyFile "/mnt/data/your_key.key"
> 
>   ServerAdmin ${APACHE_SERVER_ADMIN}
>   DocumentRoot ${APACHE_DOCUMENT_ROOT}
> 
>   ErrorLog ${APACHE_ERROR_LOG}
>   CustomLog ${APACHE_ACCESS_LOG} ${APACHE_LOG_FORMAT}
> 
>   <Directory ${APACHE_DOCUMENT_ROOT}>
>     AllowOverride All
>     Options -Indexes +FollowSymlinks
>   </Directory>
> </VirtualHost>

where your_cert.crt and your_key.key are your SSL keys that you can generate with the usual openssl keygen method. Put them in var/lib/docker/volumes/owncloud_files/_data. You could also probably point to the auto-generated certs "/etc/ssl/private/ssl-cert-snakeoil.key" and "/etc/ssl/certs/ssl-cert-snakeoil.pem".

Modify your docker-compose.yaml file to forward the https port and use your modified image:

services:
  owncloud:
    #image: owncloud/server:${OWNCLOUD_VERSION}
    image: owncloud_custom:${OWNCLOUD_VERSION}
    restart: always
    ports:
      - ${HTTP_PORT}:8080
      - "443:443"

I think that is everything. You should now be able to start your docker container with "docker-compose up -d". If you update your docker container you probably will only need to do steps 1-3 again. I'm sure there is a more elegant way to do this with inherited containers but I haven't looked into that yet. Unless there is some reason not to, it would be really nice if the container maintainer made the changes permanent. Hope this helps someone.

**Comment by tboerger** [comment]
We have removed the ssl support on purpose. You should use a proper reverse proxy (which is totally common for docker deployments) for ssl termination. There are absolutely no plans to add back ssl support to this container.

**Comment by marcelopasin** [comment]
Thank you @omegahelix77 for taking your time preparing a solution. On the other hand, I understand @tboerger and I even agree with his idea. I was just asking to remove the misleading information in the README.md.

BTW, since it is simple, why not including the reverse proxy in the docker compose already?

**Comment by omegahelix77** [comment]
Sure. I checked out nginx reverse proxy and I see the value of it. I also
agree the readme should be changed. It would take just a few minutes and
keep folks from going down the wrong path.

**Comment by tboerger** [comment]
The local README is absolutely minimal now, every documentation related part is shifted to the docs repository.
