### ISSUE TITLE
.well-known/dav always redirects to port 8080

### ISSUE THREAD

**Issue by Blizzard26** [owncloud-docker/server#124]
I have set-up my owncloud container to be exposed on port 80 instead of 8080 (plus nginx proxy for https on port 443). However, /.well-known/dav and /.well-known/caldav used by some apps to discover dav / caldav endpoints always redirect to port 8080 which is not accessible on my setup.

![grafik](https://user-images.githubusercontent.com/21283833/56614357-260b4880-6619-11e9-9b29-2cbe5054a5d1.png)

This prevent apps (e.g., CalDav / CardDav for Android) from connecting based on the pure URL.

I think it should be possible to specify the ports used inside the container.

There is a workaround by directly specifying domain.tld/remote.php/dav or domain.tld/remote.php/caldav as URL in the app. But this is not so straight forward for most users.

**Comment by tboerger** [comment]
@DeepDiver1975 where does this .well-known definition come from? For our demo at https://demo.owncloud.org/.well-known/dav it doesn't redirect to anything else than the files app.

**Comment by Blizzard26** [comment]
In this case it's the Calendar and Contacts plugins. The rerouting is done in the .htaccess file. There are several other rewrite definitions there. The .well-known directory is an RFC (https://tools.ietf.org/html/rfc5785) for service discovery and other things.

**Comment by tboerger** [comment]
I just checked it, IMHO it's an issue within the contacts and calendar apps, they are not generating the URLs in a proper way.

**Comment by Blizzard26** [comment]
Well I'm not so sure about that. This is the `.htaccess` from a plain owncloud instance (bootstrapped from a fresh docker-image; no data, clean database)
```
<IfModule mod_rewrite.c>
  RewriteEngine on
  RewriteRule .* - [env=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
  RewriteRule ^\.well-known/host-meta /public.php?service=host-meta [QSA,L]
  RewriteRule ^\.well-known/host-meta\.json /public.php?service=host-meta-json [QSA,L]
  RewriteRule ^\.well-known/carddav /remote.php/dav/ [R=301,L]
  RewriteRule ^\.well-known/caldav /remote.php/dav/ [R=301,L]
  RewriteRule ^remote/(.*) remote.php [QSA,L]
  RewriteRule ^(?:build|tests|config|lib|3rdparty|templates)/.* - [R=404,L]
  RewriteCond %{REQUEST_URI} !^/.well-known/(acme-challenge|pki-validation)/.*
  RewriteRule ^(?:\.|autotest|occ|issue|indie|db_|console).* - [R=404,L]
</IfModule>
```
There are several similar rewrite rules, e.g., also for `.well-known/host-meta`. By the way, rewrites for carddav and caldav exist also I did not install any additional plugins. So they seem to be set by default.

**Comment by tboerger** [comment]
Yeah already got that topic within our internal chat with @deepdiver1975.
