### ISSUE TITLE
Error while trying to create admin user

### ISSUE THREAD

**Issue by lnx1288** [owncloud-docker/server#126]
I'm trying to setup owncloud following the instructions in [here](https://doc.owncloud.com/server/admin_manual/installation/docker/) with the below files but get an error `Error while trying to create admin user: Failed to connect to the database: An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'owncloud'@'oc-server_owncloud_1.oc-server_default' (using password: YES)`.

My .env:
`OWNCLOUD_VERSION=latest
OWNCLOUD_DOMAIN=127.0.0.1
ADMIN_USERNAME=admin
ADMIN_PASSWORD=admin
HTTP_PORT=8080
HTTPS_PORT=443`

My .yml file:
`version: '2.1'`
`volumes:`
`  files:`
`    driver: local`
`  mysql:`
`    driver: local`
`  backup:`
`    driver: local`
`  redis:`
`    driver: local`
`services:`
`  owncloud:`
`    image: owncloud/server:${OWNCLOUD_VERSION}`
`    restart: always`
`    ports:`
`      - ${HTTP_PORT}:8080`
`    depends_on:`
`      - db`
`      - redis`
`    environment:`
`      - OWNCLOUD_DOMAIN=${OWNCLOUD_DOMAIN}`
`      - OWNCLOUD_DB_TYPE=mysql`
`      - OWNCLOUD_DB_NAME=owncloud`
`      - OWNCLOUD_DB_USERNAME=owncloud`
`      - OWNCLOUD_DB_PASSWORD=owncloud`
`      - OWNCLOUD_DB_HOST=db`
`      - OWNCLOUD_ADMIN_USERNAME=${ADMIN_USERNAME}`
`      - OWNCLOUD_ADMIN_PASSWORD=${ADMIN_PASSWORD}`
`      - OWNCLOUD_REDIS_ENABLED=true`
`      - OWNCLOUD_REDIS_HOST=redis`
`    healthcheck:`
`      test: ["CMD", "/usr/bin/healthcheck"]`
`      interval: 30s`
`      timeout: 10s`
`      retries: 5`
`    volumes:`
`      - files:/mnt/data`
`  db:`
`    image: webhippie/mariadb:latest`
`    restart: always`
`    environment:`
`      - MARIADB_ROOT_PASSWORD=owncloud`
`      - MARIADB_USERNAME=owncloud`
`      - MARIADB_PASSWORD=owncloud`
`      - MARIADB_DATABASE=owncloud`
`      - MARIADB_MAX_ALLOWED_PACKET=128M`
`      - MARIADB_INNODB_LOG_FILE_SIZE=64M`
`    healthcheck:`
`      test: ["CMD", "/usr/bin/healthcheck"]`
`      interval: 30s`
`      timeout: 10s`
`      retries: 5`
`    volumes:`
`      - mysql:/var/lib/mysql`
`      - backup:/var/lib/backup`
`  redis:`
`    image: webhippie/redis:latest`
`    restart: always`
`    environment:`
`      - REDIS_DATABASES=1`
`    healthcheck:`
`      test: ["CMD", "/usr/bin/healthcheck"]`
`      interval: 30s`
`      timeout: 10s`
`      retries: 5`
`    volumes:`
`      - redis:/var/lib/redis`

The ERROR I am getting:
oc-server_redis_1 is up-to-date
Recreating d354f4f8b148_oc-server_db_1 ... done
Recreating oc-server_owncloud_1        ... done
Attaching to oc-server_redis_1, oc-server_db_1, oc-server_owncloud_1
owncloud_1  | Creating volume folders...
owncloud_1  | Creating hook folders...
db_1        | Cron is enabled, launching it!
owncloud_1  | Waiting for MySQL...
owncloud_1  | wait-for-it: waiting 180 seconds for db:3306
db_1        | Starting cron daemon now...
owncloud_1  | wait-for-it: db:3306 is available after 0 seconds
db_1        | > writing mariadb config
db_1        | gomplate version 3.1.0, build 2f357bd5 (2018-11-30T02:51:11Z)
db_1        | config is:
db_1        | input: /etc/templates/my.cnf.tmpl
db_1        | output: /etc/mysql/my.cnf
db_1        |
owncloud_1  | Waiting for Redis...
db_1        | rendered 1 template(s) with 0 error(s) in 857.892µs
redis_1     | > chown data directory
redis_1     | > starting redis service
redis_1     | 11:C 03 May 2019 15:56:49.148 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis_1     | 11:C 03 May 2019 15:56:49.148 # Redis version=5.0.4, bits=64, commit=780041a8, modified=0, pid=11, just started
redis_1     | 11:C 03 May 2019 15:56:49.148 # Configuration loaded
redis_1     | 11:M 03 May 2019 15:56:49.150 * Running mode=standalone, port=6379.
redis_1     | 11:M 03 May 2019 15:56:49.150 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
redis_1     | 11:M 03 May 2019 15:56:49.150 # Server initialized
redis_1     | 11:M 03 May 2019 15:56:49.150 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
redis_1     | 11:M 03 May 2019 15:56:49.150 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
redis_1     | 11:M 03 May 2019 15:56:49.150 * Ready to accept connections
redis_1     | 11:signal-handler (1556899303) Received SIGTERM scheduling shutdown...
redis_1     | > chown data directory
redis_1     | > starting redis service
redis_1     | 12:C 03 May 2019 16:03:59.131 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis_1     | 12:C 03 May 2019 16:03:59.131 # Redis version=5.0.4, bits=64, commit=780041a8, modified=0, pid=12, just started
redis_1     | 12:C 03 May 2019 16:03:59.131 # Configuration loaded
redis_1     | 12:M 03 May 2019 16:03:59.133 * Running mode=standalone, port=6379.
redis_1     | 12:M 03 May 2019 16:03:59.134 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
redis_1     | 12:M 03 May 2019 16:03:59.134 # Server initialized
redis_1     | 12:M 03 May 2019 16:03:59.134 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
redis_1     | 12:M 03 May 2019 16:03:59.134 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
redis_1     | 12:M 03 May 2019 16:03:59.134 * Ready to accept connections
redis_1     | > chown data directory
redis_1     | > starting redis service
redis_1     | 12:C 03 May 2019 16:22:07.279 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis_1     | 12:C 03 May 2019 16:22:07.279 # Redis version=5.0.4, bits=64, commit=780041a8, modified=0, pid=12, just started
redis_1     | 12:C 03 May 2019 16:22:07.279 # Configuration loaded
redis_1     | 12:M 03 May 2019 16:22:07.281 * Running mode=standalone, port=6379.
redis_1     | 12:M 03 May 2019 16:22:07.281 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
redis_1     | 12:M 03 May 2019 16:22:07.281 # Server initialized
redis_1     | 12:M 03 May 2019 16:22:07.281 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
redis_1     | 12:M 03 May 2019 16:22:07.281 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
redis_1     | 12:M 03 May 2019 16:22:07.281 * Ready to accept connections
redis_1     | > chown data directory
redis_1     | > starting redis service
redis_1     | 11:C 03 May 2019 16:24:06.419 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis_1     | 11:C 03 May 2019 16:24:06.419 # Redis version=5.0.4, bits=64, commit=780041a8, modified=0, pid=11, just started
redis_1     | 11:C 03 May 2019 16:24:06.419 # Configuration loaded
redis_1     | 11:M 03 May 2019 16:24:06.420 * Running mode=standalone, port=6379.
redis_1     | 11:M 03 May 2019 16:24:06.421 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
redis_1     | 11:M 03 May 2019 16:24:06.421 # Server initialized
redis_1     | 11:M 03 May 2019 16:24:06.421 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
redis_1     | 11:M 03 May 2019 16:24:06.421 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
redis_1     | 11:M 03 May 2019 16:24:06.421 * Ready to accept connections
redis_1     | 11:signal-handler (1556900742) Received SIGTERM scheduling shutdown...
redis_1     | > chown data directory
redis_1     | > starting redis service
redis_1     | 13:C 03 May 2019 16:26:19.760 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis_1     | 13:C 03 May 2019 16:26:19.760 # Redis version=5.0.4, bits=64, commit=780041a8, modified=0, pid=13, just started
redis_1     | 13:C 03 May 2019 16:26:19.760 # Configuration loaded
redis_1     | 13:M 03 May 2019 16:26:19.763 * Running mode=standalone, port=6379.
redis_1     | 13:M 03 May 2019 16:26:19.763 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
redis_1     | 13:M 03 May 2019 16:26:19.763 # Server initialized
redis_1     | 13:M 03 May 2019 16:26:19.763 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
redis_1     | 13:M 03 May 2019 16:26:19.763 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
redis_1     | 13:M 03 May 2019 16:26:19.763 * Ready to accept connections
redis_1     | 13:signal-handler (1556901459) Received SIGTERM scheduling shutdown...
redis_1     | > chown data directory
redis_1     | > starting redis service
redis_1     | 12:C 03 May 2019 16:44:16.347 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis_1     | 12:C 03 May 2019 16:44:16.347 # Redis version=5.0.4, bits=64, commit=780041a8, modified=0, pid=12, just started
redis_1     | 12:C 03 May 2019 16:44:16.347 # Configuration loaded
owncloud_1  | wait-for-it: waiting 60 seconds for redis:6379
db_1        | > chown data directory
redis_1     | 12:M 03 May 2019 16:44:16.349 * Running mode=standalone, port=6379.
redis_1     | 12:M 03 May 2019 16:44:16.349 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
redis_1     | 12:M 03 May 2019 16:44:16.349 # Server initialized
redis_1     | 12:M 03 May 2019 16:44:16.349 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
redis_1     | 12:M 03 May 2019 16:44:16.349 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
redis_1     | 12:M 03 May 2019 16:44:16.349 * Ready to accept connections
redis_1     | 12:signal-handler (1556901886) Received SIGTERM scheduling shutdown...
redis_1     | 12:M 03 May 2019 16:44:46.551 # User requested shutdown...
redis_1     | 12:M 03 May 2019 16:44:46.551 # Redis is now ready to exit, bye bye...
redis_1     | > chown data directory
redis_1     | > starting redis service
redis_1     | 12:C 03 May 2019 16:46:07.963 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis_1     | 12:C 03 May 2019 16:46:07.963 # Redis version=5.0.4, bits=64, commit=780041a8, modified=0, pid=12, just started
redis_1     | 12:C 03 May 2019 16:46:07.963 # Configuration loaded
redis_1     | 12:M 03 May 2019 16:46:07.993 * Running mode=standalone, port=6379.
redis_1     | 12:M 03 May 2019 16:46:07.994 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
redis_1     | 12:M 03 May 2019 16:46:07.994 # Server initialized
redis_1     | 12:M 03 May 2019 16:46:07.994 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
redis_1     | 12:M 03 May 2019 16:46:07.994 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
redis_1     | 12:M 03 May 2019 16:46:07.994 * Ready to accept connections
redis_1     | 12:signal-handler (1556901994) Received SIGTERM scheduling shutdown...
redis_1     | > chown data directory
redis_1     | > starting redis service
redis_1     | 11:C 03 May 2019 16:58:37.062 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis_1     | 11:C 03 May 2019 16:58:37.062 # Redis version=5.0.4, bits=64, commit=780041a8, modified=0, pid=11, just started
redis_1     | 11:C 03 May 2019 16:58:37.062 # Configuration loaded
redis_1     | 11:M 03 May 2019 16:58:37.063 * Running mode=standalone, port=6379.
redis_1     | 11:M 03 May 2019 16:58:37.063 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
redis_1     | 11:M 03 May 2019 16:58:37.063 # Server initialized
redis_1     | 11:M 03 May 2019 16:58:37.063 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
redis_1     | 11:M 03 May 2019 16:58:37.063 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
db_1        | > starting mariadb service
redis_1     | 11:M 03 May 2019 16:58:37.064 * Ready to accept connections
db_1        | 190503 16:58:52 mysqld_safe Logging to '/var/lib/mysql/f99f18a6d580.err'.
db_1        | 190503 16:58:52 mysqld_safe Starting mysqld daemon with databases from /var/lib/mysql
owncloud_1  | wait-for-it: redis:6379 is available after 0 seconds
owncloud_1  | Removing custom folder...
owncloud_1  | Linking custom folder...
owncloud_1  | Removing config folder...
owncloud_1  | Linking config folder...
owncloud_1  | Writing config file...
owncloud_1  | Fixing base perms...
owncloud_1  | Fixing data perms...
owncloud_1  | Fixing hook perms...
owncloud_1  | Installing server database...
owncloud_1  | Error while trying to create admin user: Failed to connect to the database: An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'owncloud'@'oc-server_owncloud_1.oc-server_default' (using password: YES)
owncloud_1  |  ->
owncloud_1  | Fixing base perms...
owncloud_1  | Fixing data perms...
owncloud_1  | Fixing hook perms...
owncloud_1  | Installing server database...
owncloud_1  | Error while trying to create admin user: Failed to connect to the database: An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'owncloud'@'oc-server_owncloud_1.oc-server_default' (using password: YES)
owncloud_1  |  ->
oc-server_owncloud_1 exited with code 1
owncloud_1  | Fixing base perms...
owncloud_1  | Fixing data perms...
owncloud_1  | Fixing hook perms...
owncloud_1  | Installing server database...
owncloud_1  | Error while trying to create admin user: Failed to connect to the database: An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'owncloud'@'oc-server_owncloud_1.oc-server_default' (using password: YES)

**Comment by tboerger** [comment]
If owncloud can't connect to the database it won't work. Use whichever database works for you, the docs only mention a reference which works for most platforms, but there are known issues with the volumes in centos.

If you provide a working database the image is working fine.

**Comment by BluGeni** [comment]
The docker-compose example given in the docs does not work and gives this error. Maybe updating the docs to point to a database that works would be helpful.

**Comment by ThomDietrich** [comment]
As @tboerger said, just use any other, like the most obvious of all (as I do):

```yaml
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: owncloud
      MYSQL_DATABASE: owncloud
      MYSQL_USER: owncloud
      MYSQL_PASSWORD: owncloud
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    volumes:
      - ./mysql:/var/lib/mysql
```
