### ISSUE TITLE
occ files:scan --all not working

### ISSUE THREAD

**Issue by PhiGi87** [owncloud-docker/server#13]
Hey,

When I run the following command it comes to an error:
`docker exec -ti 200_1mcw.oncloud.zone occ files:scan --all`

> Scanning files for 4 users
> Starting scan for user 1 out of 4 (user1)
> Home storage for user user1 not writable
> Make sure you're running the scan command only as the user the web server runs as
> Starting scan for user 2 out of 4 (admin)
> Home storage for user admin not writable
> Make sure you're running the scan command only as the user the web server runs as
> Starting scan for user 3 out of 4 (user2)
> Starting scan for user 4 out of 4 (user3)
> Home storage for user user3 not writable
> Make sure you're running the scan command only as the user the web server runs as

But the directory is writable.

What could be the problem?

Thanks for Help.

**Comment by tboerger** [comment]
I can't reproduce that issue, can you tell more details how you launched and configured it?

**Comment by tboerger** [comment]
Just tried it within one of my demo containers:

```
$ docker-compose exec web occ files:scan --all
Starting scan for user 1 out of 1 (admin)

+---------+-------+--------------+
| Folders | Files | Elapsed time |
+---------+-------+--------------+
| 8       | 8     | 00:00:00     |
+---------+-------+--------------+
```

**Comment by PhiGi87** [comment]
Sorry I have just seen that here was answered or closed.

I have imported data from a backup into a newly installed cloud, the MySQL table is replaced, and the docker container is rebooted. Then the error occurs when scanning.

Do you like to see this directly on my server? I do not understand why it is not running. :(

**Comment by tboerger** [comment]
And who is the owner of the files?

**Comment by PhiGi87** [comment]
www-data is owner of the directory

**Comment by tboerger** [comment]
I will ask within the engineering team if somebody got an idea. I have no idea where this comes from yet

**Comment by PhiGi87** [comment]
Do you want to look at the server? Perhaps I overlook something.

**Comment by tboerger** [comment]
If you can give me access I can take a look later today

**Comment by PhiGi87** [comment]
Can i send you access data via mail? Or how would you like it?

**Comment by tboerger** [comment]
Send it via Mail to tboerger@owncloud.com
