### ISSUE TITLE
Mariadb container core dumps after starting on raspbian.

### ISSUE THREAD

**Issue by psaleh** [owncloud-docker/server#133]
`docker run -d   --name mariadb   -e MARIADB_ROOT_PASSWORD=owncloud   -e MARIADB_USERNAME=owncloud   -e MARIADB_PASSWORD=owncloud   -e MARIADB_DATABASE=owncloud   --volume owncloud_mysql:/var/lib/mysql --volume owncloud_backup:/var/lib/backup   webhippie/mariadb:latest
5e43f243881cd74ea7276ba8c6790e73c1f2727a978cb59d4a317c68a093d352

pi@picloud:~ $ docker container logs mariadb
Cron is enabled, launching it!
Starting cron daemon now...
> writing mariadb config
./setup: line 7:    17 Illegal instruction     (core dumped) /usr/bin/gomplate -V -o /etc/mysql/my.cnf -f /etc/templates/my.cnf.tmpl

**Comment by tboerger** [comment]
Not related to this repository.
