### ISSUE TITLE
Make sure Apache Timeout is set to a high value?

### ISSUE THREAD

**Issue by guruz** [owncloud-docker/server#134]
I was experiencing 'Locked' issues with demo.owncloud.com and didn't really know the cause.
When reading an unrelated thread here https://central.owncloud.org/t/423-locked-on-move-after-upload-is-finished-and-also-400-the-computed-checksum-does-not-match-the-one-received-from-the-client/20277/21 I noticed this could be caused by the Apache "Timeout" directive when handling the MOVE call of an upload (chunk assembly)

I see you initialize this value with 300:
https://github.com/owncloud-docker/php/search?q=APACHE_TIMEOUT&unscoped_q=APACHE_TIMEOUT

Would it make sense to have a higher value for this here for owncloud?
I can't prove yet this is the issue, but it might?

Or maybe it's unrelated since the reporter on central is using php-fpm and not an Apache module...hmm
Because the timeout here just mentions TCP etc: https://httpd.apache.org/docs/2.4/mod/core.html#timeout

CC @pvince81

**Comment by tboerger** [comment]
I'm currently applying a value of 1200 to our demos, than you can verify if it is really the root couse of it.

**Comment by tboerger** [comment]
@guruz any update?
