### ISSUE TITLE
Openshift/Docker - Trying to setup test version of production owncloud to test upgrade from 10.0.10 to 10.1.0

### ISSUE THREAD

**Issue by lukastheblack** [owncloud-docker/server#135]
I have an Openshift  Owncloud deployment, and the deployment itself has worked great for 12 months, currently using the  docker.io/owncloud:10.0.10-apache image. I decided that having a test deployment would be useful to determine any possible issues to resolve during the upgrade process. I have done so by creating a snapshot of the current working database, and copying the deployment, prepending test- to the beginning of all names -- deployment name is test-owncloud -- Openshift Route and URL are test-owcloud.mydomain.com . I built 10.1.0 first using owncloud/base:bionic (FROM owncloud/base:bionic)
See attached dockerfile below. The upgrade process goes fairly smoothly, though I do need to do the following to my database before the upgrade can proceed.
ALTER TABLE public.oc_accounts ADD CONSTRAINT oc_accounts_ukey unique (id) 

Once the upgrade is complete, the webserver comes up, and I get a login page, but it immediate refreshes when I attempt to login, saying "you took too long to login, try again" -- In the logs I see 

{"reqId":"nDiA7mWqEWi21Lb45JTa","level":3,"time":"2019-06-08T14:30:39-05:00","remoteAddr":"","user":"--","app":"PHP","method":"--","url":"--","message":"str_repeat(): Second argument has to be greater than or equal to 0 at \/var\/www\/html\/lib\/composer\/symfony\/console\/Helper\/ProgressBar.php#509"}
{"reqId":"nDiA7mWqEWi21Lb45JTa","level":3,"time":"2019-06-08T14:30:39-05:00","remoteAddr":"","user":"--","app":"PHP","method":"--","url":"--","message":"str_repeat(): Second argument has to be greater than or equal to 0 at \/var\/www\/html\/lib\/composer\/symfony\/console\/Helper\/ProgressBar.php#509"}
{"reqId":"nDiA7mWqEWi21Lb45JTa","level":3,"time":"2019-06-08T14:30:39-05:00","remoteAddr":"","user":"--","app":"PHP","method":"--","url":"--","message":"str_repeat(): Second argument has to be greater than or equal to 0 at \/var\/www\/html\/lib\/composer\/symfony\/console\/Helper\/ProgressBar.php#509"}
{"reqId":"nDiA7mWqEWi21Lb45JTa","level":3,"time":"2019-06-08T14:30:39-05:00","remoteAddr":"","user":"--","app":"PHP","method":"--","url":"--","message":"str_repeat(): Second argument has to be greater than or equal to 0 at \/var\/www\/html\/lib\/composer\/symfony\/console\/Helper\/ProgressBar.php#509"}
{"reqId":"nDiA7mWqEWi21Lb45JTa","level":3,"time":"2019-06-08T14:30:39-05:00","remoteAddr":"","user":"--","app":"PHP","method":"--","url":"--","message":"str_repeat(): Second argument has to be greater than or equal to 0 at \/var\/www\/html\/lib\/composer\/symfony\/console\/Helper\/ProgressBar.php#509"}
{"reqId":"nDiA7mWqEWi21Lb45JTa","level":3,"time":"2019-06-08T14:30:39-05:00","remoteAddr":"","user":"--","app":"PHP","method":"--","url":"--","message":"str_repeat(): Second argument has to be greater than or equal to 0 at \/var\/www\/html\/lib\/composer\/symfony\/console\/Helper\/ProgressBar.php#509"}
{"reqId":"nDiA7mWqEWi21Lb45JTa","level":3,"time":"2019-06-08T14:30:39-05:00","remoteAddr":"","user":"--","app":"PHP","method":"--","url":"--","message":"str_repeat(): Second argument has to be greater than or equal to 0 at \/var\/www\/html\/lib\/composer\/symfony\/console\/Helper\/ProgressBar.php#509"}
{"reqId":"nDiA7mWqEWi21Lb45JTa","level":3,"time":"2019-06-08T14:30:39-05:00","remoteAddr":"","user":"--","app":"PHP","method":"--","url":"--","message":"str_repeat(): Second argument has to be greater than or equal to 0 at \/var\/www\/html\/lib\/composer\/symfony\/console\/Helper\/ProgressBar.php#509"}
{"reqId":"nDiA7mWqEWi21Lb45JTa","level":3,"time":"2019-06-08T14:30:39-05:00","remoteAddr":"","user":"--","app":"PHP","method":"--","url":"--","message":"str_repeat(): Second argument has to be greater than or equal to 0 at \/var\/www\/html\/lib\/composer\/symfony\/console\/Helper\/ProgressBar.php#509"}
{"reqId":"nDiA7mWqEWi21Lb45JTa","level":3,"time":"2019-06-08T14:30:39-05:00","remoteAddr":"","user":"--","app":"PHP","method":"--","url":"--","message":"str_repeat(): Second argument has to be greater than or equal to 0 at \/var\/www\/html\/lib\/composer\/symfony\/console\/Helper\/ProgressBar.php#509"}
{"reqId":"CZDqDpdEsZQKBGnuPoiR","level":0,"time":"2019-06-08T14:49:30-05:00","remoteAddr":"10.18.2.1","user":"--","app":"no app in context","method":"POST","url":"\/index.php\/login","message":"CSRF check failed"}_

**If I add 'csrf.diabled' => true, to my config.php , I get** 

{"reqId":"E6fUdb9mlYywP8uQUqee","level":0,"time":"2019-06-08T14:52:29-05:00","remoteAddr":"10.19.2.1","user":"--","app":"OC\\User\\Session::login","method":"POST","url":"\/index.php\/login","message":"regenerating session id for uid REDACTED-USER, password set"}
{"reqId":"E6fUdb9mlYywP8uQUqee","level":0,"time":"2019-06-08T14:52:29-05:00","remoteAddr":"10.19.2.1","user":"--","app":"OC\\Authentication\\Token\\DefaultTokenProvider::getToken","method":"POST","url":"\/index.php\/login","message":"token 619b6ea7c7d0bb1d46cdd7e1d365eb0794a7f213d542ccdaa6d1cd0135487d28b1dc03193b8163b43a2ca0fadd1042ea0539e7aafb5656c7576594592ff9e337 does not exist"}
{"reqId":"E6fUdb9mlYywP8uQUqee","level":0,"time":"2019-06-08T14:52:29-05:00","remoteAddr":"10.19.2.1","user":"--","app":"OC\\User\\Session::validateToken","method":"POST","url":"\/index.php\/login","message":"token 619b6ea7c7d0bb1d46cdd7e1d365eb0794a7f213d542ccdaa6d1cd0135487d28b1dc03193b8163b43a2ca0fadd1042ea0539e7aafb5656c7576594592ff9e337, not found"}
{"reqId":"E6fUdb9mlYywP8uQUqee","level":0,"time":"2019-06-08T14:52:29-05:00","remoteAddr":"10.19.2.1","user":"REDACTED-USER","app":"user_ldap","method":"POST","url":"\/index.php\/login","message":"No DN found for <REDACTED-USER> on ldaps:\/\/REDACTED-LDAP-SERVER"}
{"reqId":"E6fUdb9mlYywP8uQUqee","level":3,"time":"2019-06-08T14:52:29-05:00","remoteAddr":"10.19.2.1","user":"REDACTED-USER","app":"OC\\User\\Session::createSessionToken","method":"POST","url":"\/index.php\/login","message":"Exception: {\"Exception\":\"OCP\\\\Session\\\\Exceptions\\\\SessionNotAvailableException\",\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Session\\\/CryptoSessionData.php(159): OC\\\\Session\\\\Internal->getId()\\n#1 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/User\\\/Session.php(723): OC\\\\Session\\\\CryptoSessionData->getId()\\n#2 \\\/var\\\/www\\\/html\\\/core\\\/Controller\\\/LoginController.php(231): OC\\\\User\\\\Session->createSessionToken(Object(OC\\\\AppFramework\\\\Http\\\\Request), 'REDACTED-USER', 'REDACTED-USER', 'REDACTED')\\n#3 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(153): OC\\\\Core\\\\Controller\\\\LoginController->tryLogin(*** sensitive parameters replaced ***)\\n#4 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(85): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OC\\\\Core\\\\Controller\\\\LoginController), 'tryLogin')\\n#5 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/AppFramework\\\/App.php(100): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OC\\\\Core\\\\Controller\\\\LoginController), 'tryLogin')\\n#6 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(46): OC\\\\AppFramework\\\\App::main('LoginController', 'tryLogin', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#7 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Route\\\/Router.php(342): OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#8 \\\/var\\\/www\\\/html\\\/lib\\\/base.php(909): OC\\\\Route\\\\Router->match('\\\/login')\\n#9 \\\/var\\\/www\\\/html\\\/index.php(54): OC::handleRequest()\\n#10 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Session\\\/Internal.php\",\"Line\":130}"}
{"reqId":"5Ce7xn6pZ56lnOkt23lm","level":0,"time":"2019-06-08T14:52:29-05:00","remoteAddr":"10.19.2.1","user":"--","app":"no app in context","method":"GET","url":"\/index.php\/login\/selectchallenge","message":"Current user is not logged in"}

Any help on this issue would be greatly appreciated, I find myself fresh out of ideas on how to approach the problem.

Dockerfile
[dockerfile.txt](https://github.com/owncloud-docker/server/files/3268876/dockerfile.txt)
I am not attaching the run.sh script to this post but this is what it does
mv /var/www/owncloud/* $OWNCLOUD_DIR/
apachectl -f /etc/apache2/apache2.conf -DFOREGROUND
tail -f $OWNCLOUD_DIR/oc.log

**Comment by tboerger** [comment]
Mixing docker.io/owncloud:10.0.10-apache with one of our owncloud images isn't something I can support. These images have nearly nothing in common, feel free to contact docker Inc as they are maintaining this image.

We got a working openshift template published at https://github.com/owncloud-docker/openshift

**Comment by lukastheblack** [comment]
If I use my your openshift template, would I be able to mount my apps and data directory, as well as use my current database?

**Comment by tboerger** [comment]
I guess not directly, I don't remember how the docker Inc docker images define the volumes.

**Comment by lukastheblack** [comment]
Their dockerfile seems to define /var/www/html for volumes, but no other volume directives are listed. My data and apps (Openshift)volumes are subdirectories of /var/www/html, why would that cause an issue? As far as I can tell, both docker images download and unpack the owncloud tars at runtime, then change the ownership before starting the web server.

**Comment by tboerger** [comment]
That's not how the docker images maintained by us work...
