### ISSUE TITLE
Market apps disappearing afer restarting the stack

### ISSUE THREAD

**Issue by baptisteArnaud** [owncloud-docker/server#136]
I deployed the server on my Kubernetes cluster. Whenever I restart the deployment, it seems not to have memorized installed apps from Market. Is this an expected behavior?

I have 4 mounted volumes as expected : 
- data
- config
- mysql
- redis

What should I do in order to keep track of installed apps and their configs?

To reproduce:

Server version 10.0.10
Market version 0.2.5

- Install any app using Market app (i.e. Calendar app).
- Restart the entire docker stack (after removing every containers to avoid memorized state).
- Login
- No apps installed

**Comment by tboerger** [comment]
All installed apps are stored on the volume /mnt/data/apps, so if you are losing the apps it's an indicator that you are not storing all volumes persistently.

**Comment by baptisteArnaud** [comment]
Thanks for pointing that out. :)

It seems that in version 10.0.10, the `apps` folder is located outside the `data` folder. I need to persist it separatly. ( It's a shame you don't support ARM image :'( )

**Comment by tboerger** [comment]
The only folder you need to mount by default is /mnt/data, than everything is persisted properly.
