### ISSUE TITLE
Login not working

### ISSUE THREAD

**Issue by Schack17** [owncloud-docker/server#14]
Hi,

I can't get the ldap login working. It fails with this error:
OCP Files NotFoundException
{"reqId":"9pyYHqzCpkXEuoScGAv8","level":3,"time":"2017-07-08T13:36:35+00:00","remoteAddr":"_private_","user":"_myuser_","app":"index","method":"GET","url":"\/index.php\/apps\/files\/","message":"Exception: {\"Exception\":\"OCP\\\\Files\\\\NotFoundException\",\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files\\\/lib\\\/Controller\\\/ViewController.php(132): OC_Helper::getStorageInfo('\\\/', false)\\n#1 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files\\\/lib\\\/Controller\\\/ViewController.php(203): OCA\\\\Files\\\\Controller\\\\ViewController->getStorageInfo()\\n#2 [internal function]: OCA\\\\Files\\\\Controller\\\\ViewController->index('', '', NULL)\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(159): call_user_func_array(Array, Array)\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Files\\\\Controller\\\\ViewController), 'index')\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(98): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Files\\\\Controller\\\\ViewController), 'index')\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(46): OC\\\\AppFramework\\\\App::main('ViewController', 'index', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#7 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#8 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Router.php(299): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#9 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(918): OC\\\\Route\\\\Router->match('\\\/apps\\\/files\\\/')\\n#10 \\\/var\\\/www\\\/owncloud\\\/index.php(49): OC::handleRequest()\\n#11 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/helper.php\",\"Line\":570}"}

LDAP Config is ok. After a new ldap-user tried to login, the new login is listet in the groups view.
For "User Home Folder Naming Rule" I have tried uid, cn, samaccountname. Nothing works.

My system settings:
Redis container like doc.
Docker Data container: sudo create volume ocdata
I can found new files in this container, so I think it works.

Created a owncloud docker instance with:
sudo docker run -d \
  --name owncloud \
  --link redis:redis \
  --restart always \
  -p 80:80 \
  -p 443:443 \
  -e OWNCLOUD_DOMAIN=$DOMAIN \
  -e OWNCLOUD_DB_TYPE=mysql \
  -e OWNCLOUD_DB_NAME=ownclouddb \
  -e OWNCLOUD_DB_USERNAME=owncloud \
  -e OWNCLOUD_DB_PASSWORD=$MYSQL_OC_PASSWORD \
  -e OWNCLOUD_DB_HOST=$DB_HOST \
  -e OWNCLOUD_ADMIN_USERNAME=admin \
  -e OWNCLOUD_ADMIN_PASSWORD=$ADMIN_OC_PASSWORD \
  -e OWNCLOUD_REDIS_ENABLED=true \
  -e OWNCLOUD_REDIS_HOST=redis \
  -e OWNCLOUD_DEFAULT_LANGUAGE=de \
  --volume ocdata:/mnt/data:z \
  -v /etc/letsencrypt/live/$DOMAIN/cert.pem:/mnt/data/certs/ssl-cert.crt \
  -v /etc/letsencrypt/live/$DOMAIN/privkey.pem:/mnt/data/certs/ssl-cert.key \
  $ocVer

My ldap-config:
sudo docker exec --user www-data -t owncloud /var/www/owncloud/occ ldap:show-config
+-------------------------------+--------------------------------------------------+
| Configuration                 |                                                  |
+-------------------------------+--------------------------------------------------+
| hasMemberOfFilterSupport      | 1                                                |
| hasPagedResultSupport         |                                                  |
| homeFolderNamingRule          | attr:uid                                         |
| lastJpegPhotoLookup           | 0                                                |
| ldapAgentName                 | Administrator@_mydomain_.local                        |
| ldapAgentPassword             | ***                                              |
| ldapAttributesForGroupSearch  |                                                  |
| ldapAttributesForUserSearch   |                                                  |
| ldapBackupHost                |                                                  |
| ldapBackupPort                |                                                  |
| ldapBase                      | dc=_mydomain_,dc=local                                |
| ldapBaseGroups                | dc=_mydomain_,dc=local                                |
| ldapBaseUsers                 | dc=_mydomain_,dc=local                                |
| ldapCacheTTL                  | 5                                                |
| ldapConfigurationActive       | 1                                                |
| ldapDynamicGroupMemberURL     |                                                  |
| ldapEmailAttribute            | mail                                             |
| ldapExperiencedAdmin          | 0                                                |
| ldapExpertUUIDGroupAttr       |                                                  |
| ldapExpertUUIDUserAttr        |                                                  |
| ldapExpertUsernameAttr        | sAMAccountName                                   |
| ldapGroupDisplayName          | cn                                               |
| ldapGroupFilter               | (&(|(objectclass=group)))                        |
| ldapGroupFilterGroups         |                                                  |
| ldapGroupFilterMode           | 0                                                |
| ldapGroupFilterObjectclass    | group                                            |
| ldapGroupMemberAssocAttr      | member                                           |
| ldapHost                      | _myserver_._mydomain_.local                             |
| ldapIgnoreNamingRules         |                                                  |
| ldapLoginFilter               | (&(&(|(objectclass=user)))(samaccountname=%uid)) |
| ldapLoginFilterAttributes     |                                                  |
| ldapLoginFilterEmail          | 0                                                |
| ldapLoginFilterMode           | 0                                                |
| ldapLoginFilterUsername       | 1                                                |
| ldapNestedGroups              | 0                                                |
| ldapOverrideMainServer        |                                                  |
| ldapPagingSize                | 500                                              |
| ldapPort                      | 389                                              |
| ldapQuotaAttribute            |                                                  |
| ldapQuotaDefault              |                                                  |
| ldapTLS                       | 0                                                |
| ldapUserDisplayName           | displayname                                      |
| ldapUserDisplayName2          | name                                             |
| ldapUserFilter                | (&(|(objectclass=user)))                         |
| ldapUserFilterGroups          |                                                  |
| ldapUserFilterMode            | 0                                                |
| ldapUserFilterObjectclass     | user                                             |
| ldapUuidGroupAttribute        | auto                                             |
| ldapUuidUserAttribute         | auto                                             |
| turnOffCertCheck              | 0                                                |
| useMemberOfToDetectMembership | 1                                                |
+-------------------------------+--------------------------------------------------+

What can I do?
Please help, 

Ben

**Comment by tboerger** [comment]
This sounds more like a general issue with your owncloud setup, not directly related to the docker container itself, maybe it's better to ask for help on the forum at https://central.owncloud.com

**Comment by Schack17** [comment]
I have created a new non ldap user and I got the same problem.
So It's no ldap problem.

**Comment by tboerger** [comment]
Ah, sorry... It's central.owncloud.org

And what do you get on the logs with the local user?

**Comment by Schack17** [comment]
> And what do you get on the logs with the local user?
I get the same message. See it in the first post.

> This sounds more like a general issue with your owncloud setup, not directly related to the docker container itself,
Please notice: I don't have a config file. I just use the docker params. I think it's a problem with the docker image.

The part of the documentation doesn't work:
--volume ./data:/mnt/data:z
Produce this error:
docker: Error response from daemon: create ./data: "./data" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path.
See 'docker run --help'.

So I have used 
sudo create volume ocdata
and then
--volume ocdata:/mnt/data:z

I think the documentation is wrong or it's a bug in the image. Can you check this?

**Comment by tboerger** [comment]
You can skip the :z, this is only required with selinux. You are right,./data works within docker compose but for docker run it requires absolute paths

**Comment by Schack17** [comment]
My error is the same without :z.

**Comment by felixboehm** [comment]
Please use absolut path for volume mounts with docker.
Or use docker-compose as suggested in the example usage.

If your data volume is not mounted, of course the users data folders can't be created.
Please reopen if still an issue.

**Comment by Schack17** [comment]
> If your data volume is not mounted, of course the users data folders can't be created.

In the admin account I can change any file and it is stored in the image.
But new users can not create the files-folder.
Yes, the issue is still open.

Now I try nextcloud. Owncloud is not working under ubuntu 16.04 because of php chaos. 7.1 and 5.4 are not supported. But other versions are not available in ubuntu. Package chaos.
And with docker the files-folder problem.

**Comment by tboerger** [comment]
Ubuntu 16.04 works totally fine with ownCloud, our base image is built on top of Ubuntu 16.04 from the standard repositories: https://github.com/owncloud-docker/base/blob/master/Dockerfile.

Since even demos like https://demo.owncloud.com or https://demo.owncloud.org are built on these Docker images and we can created as many users as we want your problem must be a configuration issue.

This is for sure a configuration that works on different machines:

```
version: '2'

services:
  web:
    image: owncloud/server:10.0.2
    network_mode: bridge
    environment:
      - OWNCLOUD_DOMAIN=demo.owncloud.com
      - OWNCLOUD_DB_TYPE=mysql
      - OWNCLOUD_DB_NAME=owncloud
      - OWNCLOUD_DB_USERNAME=owncloud
      - OWNCLOUD_DB_PASSWORD=owncloud
      - OWNCLOUD_DB_HOST=db
      - OWNCLOUD_ADMIN_USERNAME=admin
      - OWNCLOUD_ADMIN_PASSWORD=admin
    labels:
      - traefik.frontend.passHostHeader=true
      - traefik.frontend.rule=Host:demo.owncloud.com
      - traefik.port=80
    links:
      - db:db
    volumes:
      - /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt:ro

  db:
    image: webhippie/mariadb
    network_mode: bridge
    environment:
      - MARIADB_ROOT_PASSWORD=owncloud
      - MARIADB_USERNAME=owncloud
      - MARIADB_PASSWORD=owncloud
      - MARIADB_DATABASE=owncloud
    labels:
      - traefik.enable=false
```
