### ISSUE TITLE
Could not open input file: /var/www/owncloud/occ

### ISSUE THREAD

**Issue by rajeshc1988** [owncloud-docker/server#140]
Hi,

Could not open input file: /var/www/owncloud/occ

I am facing this issue when mounting the data from local drive to container

**Comment by tboerger** [comment]
This sounds like you are using wrong volume paths. Beside that you don't provide any details about your usage, that's why I'm closing the issue by now.

If you provide more information we could open the issue again.

**Comment by rajeshc1988** [comment]
@tboerger 

I have mount correctly but I am facing permission issue for "occ".

**Comment by tboerger** [comment]
The permissions of occ within the container are set right, so I guess you are mounting files which are not meant for mounting.
