### ISSUE TITLE
The "Installing with Docker" docs rely on docker-compose.yml

### ISSUE THREAD

**Issue by daviddavid** [owncloud-docker/server#141]
The [latest commit](https://github.com/owncloud-docker/server/commit/71369eadbb3521930c2eca116f8e2acd657b692a) removes the docker-compose.yml which the [official docs](https://doc.owncloud.com/server/admin_manual/installation/docker/) link to and rely on.

**Comment by tboerger** [comment]
The pr https://github.com/owncloud/docs/pull/1364 added the compose config to the docs. If there are still references to files within this repository report it to the docs repo.

The issue tracker on this repo will get responses to issues with the image itself, the whole documentation got to be handled by owncloud/docs.
