### ISSUE TITLE
Support for running as unprivileged  user

### ISSUE THREAD

**Issue by schnatterer** [owncloud-docker/server#146]
Is does not seem possible to run the container as non-root/unprivileged user. Which is not exactly a goot practice.

What would have to change? for running with UID !=0? Only chmod/chown?

**Comment by tboerger** [comment]
You could be able to run the container with another uid than 0 if you set OWNCLOUD_SKIP_CHOWN to true. That works already totally fine for openshift.

**Comment by schnatterer** [comment]
Thanks for your fast answer!

I set `OWNCLOUD_SKIP_CHOWN=true` in my `docker-compose.yaml`.
Startup fails with:
`/etc/entrypoint.d/98-overwrite.sh: line 12: /etc/environment: Permission denied`.

Not too surprising:

```bash
 ls -la  /etc/environment
-rw-rw-r-- 1 root root 5315 Sep  1 20:16 /etc/environment
```

Do you have any ideas how to get around this issue without building my own image with different chown/chmod?

**Comment by tboerger** [comment]
Ah, right... Openshift is using the root user with a different uid, that's why this works flawless on openshift.
