### ISSUE TITLE
no symbol link made for /mnt/data/files to /var/www/owncloud/data

### ISSUE THREAD

**Issue by Aldwyr** [owncloud-docker/server#148]
Hi everyone,
I have a issues with the last version of owncloud. 
I want to migrate my old owncloud server to docker. I see I just need to save my data on /mnt/data/files.
My config on /mnt/data/config and my custom apps on /mnt/data/apps
At the end, I have something like that on my local file : 
data/files/
data/config/
data/apps/

and on my docker-compose, I've got : 
    volumes: 
     -v /data:/mnt/data

(database and redis is okay, no problm with them)
but, when I start with that, I get only symbol link between /var/www/owncloud/config -> /mnt/data/config and /var/www/onwcloud/apps -> /mnt/apps but I don't have anything like that with files. So when I log with my account, he recreate everything but without my data. 

So, do I miss something during my configuration ? 😢

**Comment by tboerger** [comment]
If you are migrating from a non-dockerized environment you should compare the generated config.php. The docker image got a pre-defined value as env variable `OWNCLOUD_VOLUME_FILES` for the data directory which points to `/mnt/data/files`. There is not any symlink involved as the files are living outside of the webroot.

For end-user support please create a thread on https://central.owncloud.org/ or contact the support. The issue tracker is focused on confirmed bugs on the docker image.
