### ISSUE TITLE
The username is already being used

### ISSUE THREAD

**Issue by chungeli** [owncloud-docker/server#149]
After a period of normal operation of my own deployed owncloud, the login interface of the owncloud suddenly prompted me to configure the database：
After I tried to restart owncloud,the log output:
   The username is already being used
I wonder why this happens and who knows why?

**Comment by tboerger** [comment]
This only happens if the container is losing it state, which means the volume data doesn't exist anymore.

Make sure that the data is still mounted to /mnt/data.
