### ISSUE TITLE
Migrating an existing setup

### ISSUE THREAD

**Issue by ThomDietrich** [owncloud-docker/server#15]
Hello!
I'm trying to import an existing setup. I've done the following two things:

1. copy the old data folder to `./data`
2. dump and import the mysql database in mariadb

Both steps have been verified by checking inside the containers via `exec ... bash`

Now I'm seeing the following errors upon `docker-compose up`

```
owncloud_1  | Creating volume folders...
owncloud_1  | Waiting for MySQL...
owncloud_1  | wait-for-it: waiting 180 seconds for db:3306
owncloud_1  | wait-for-it: db:3306 is available after 1 seconds
owncloud_1  | Removing custom folder...
owncloud_1  | Linking custom folder...
owncloud_1  | Removing config folder...
owncloud_1  | Linking config folder...
owncloud_1  | Fixing base perms...
owncloud_1  | Fixing data perms...
owncloud_1  | Installing server database...
owncloud_1  | ownCloud is not installed - only a limited number of commands are available
owncloud_1  | The username is already being used
owncloud_1  |
owncloud_1  |
owncloud_1  |   [Symfony\Component\Console\Exception\CommandNotFoundException]
owncloud_1  |   There are no commands defined in the "config:system" namespace.
owncloud_1  |
owncloud_1  |
owncloud_1  | dpkg: error: --compare-versions takes three arguments: <version> <relation> <version>
owncloud_1  |
owncloud_1  | Type dpkg --help for help about installing and deinstalling packages [*];
owncloud_1  | Use 'apt' or 'aptitude' for user-friendly package management;
owncloud_1  | Type dpkg -Dhelp for a list of dpkg debug flag values;
owncloud_1  | Type dpkg --force-help for a list of forcing options;
owncloud_1  | Type dpkg-deb --help for help about manipulating *.deb files;
owncloud_1  |
owncloud_1  | Options marked [*] produce a lot of output - pipe it through 'less' or 'more' !
owncloud_1  | Enabling files_external app...
owncloud_1  |
owncloud_1  |
owncloud_1  |   [Symfony\Component\Console\Exception\CommandNotFoundException]
owncloud_1  |   There are no commands defined in the "config:system" namespace.
```

Any ideas what went wrong?

**Comment by ThomDietrich** [comment]
Solved. You should mention in the README, that the config is mounted from within the data folder. While you are at it, a short guide on how to migrate from a non-docker environment might help others.
Thanks for the image!

**Comment by ThomDietrich** [comment]
After adding and adapting the default config file, the system starts up fine. Sadly the files are not accessible (File not Found error via webapp). My files are encrypted, the encryption module is enabled. I've executed `occ files:scan` and `occ encryption:migrate`. Any suggestions? @tboerger

**Comment by hodyroff** [comment]
You might need the salt for the encryption from your previous config.php, IMHO

**Comment by ThomDietrich** [comment]
I did take over most of my config, including the salt.
The migration was not successful, at some point I decided to just set up a new instance and reupload everything from the clients.
