### ISSUE TITLE
how to redirect 8080 to 443 and add ssl

### ISSUE THREAD

**Issue by aratar79** [owncloud-docker/server#150]
hello sorry for my english, where I find doc to add my ssl certificate and redirect to port 443, I try to change /etc/apache2/sites-availables/default.conf but without success. I'm not a systems expert.

thanks.

**Comment by tboerger** [comment]
You should use a reverse proxy for the SSL termination. Since this is pretty common for Docker setups we have dropped the whole SSL parts from this Docker image.

You can take a look at https://owncloud.org/news/docker-owncloud-traefik-reverse-proxy-lets-encrypt-ssl/ to get an idea how to build this setup with Traefik.

**Comment by d-lareg** [comment]
The news isnt online anymore but for all who are looking for a solution, take a look at https://github.com/rorydavidson/owncloud-nginx-letsencrypt-docker.

**Comment by ThomDietrich** [comment]
Agreed, you should handle https outside the owncloud image - which is a good recommendation idea in general.
Another option: You can use a docker-host based install of caddy to serve all kinds of services through it as a proxy.

`Caddyfile`:
```
owncloud.mydomain.com {
    bind 12.23.34.45
    tls root@mydomain.com
    log /var/log/caddy/owncloud.requests.log
    proxy / http://localhost:8080 {
        websocket
        transparent
    }
    header / {
        Strict-Transport-Security "max-age=31536000;"
    }
}
```

**Comment by jack338c** [comment]
@ThomDietrich 
Hello,Coud you help me to make a Caddyfile
here are my configuration:
owncloud docker and  Caddyv2 docker are both installed on my nas(OMV),which lan ip is 10.20.30.181
owncloud access webui is 10.20.30.181:8080, and which is already port-forword by my main router
main router is enabled ddns function and has a domion(hom.xx.com) and ssl file (key and crt)

#Doker owncloud
`docker run -d \
--name=owncloud \
-e OWNCLOUD_DOMAIN=localhost:8080 \
-p 8080:8080 \
-v /mnt/owncloud:/mnt/data \
--restart unless-stopped \
owncloud/server:latest`

#Doker caddy v2
docker run -d \
  --name caddy \
  -e "ACME_AGREE=true" \
  -e "CADDYPATH=/etc/caddycerts" \
  -v /opt/caddy/certs:/etc/caddycerts \
  -v /opt/caddy/Caddyfile:/etc/Caddyfile \
  -p 80:80 -p 443:443 \
  --restart unless-stopped \
  arm64v8/caddy

**Comment by xoxys** [comment]
Please use the forum https://central.owncloud.org/ for general questions.
