### ISSUE TITLE
ERROR: for owncloud  Cannot start service owncloud:

### ISSUE THREAD

**Issue by amaurybsouza** [owncloud-docker/server#151]
Hi all,

I'm trying to install OwnCloud Server with Docker and Docker-Compose, but encountered errors while bringing up the project.

Here is the print from my terminal:

ERROR: for ownclouddockerserver_owncloud_1  Cannot start service owncloud: driver failed programming external connectivity on endpoint ownclouddockerserver_owncloud_1 (d89eaf7a7dce1239081c0466eee59ca6baee4bb3709d18cf833658c43a08a1f7): Error starting userland proxy: listen tcp 0.0.0.0:80: bind: address already in use

ERROR: for owncloud  Cannot start service owncloud: driver failed programming external connectivity on endpoint ownclouddockerserver_owncloud_1 (d89eaf7a7dce1239081c0466eee59ca6baee4bb3709d18cf833658c43a08a1f7): Error starting userland proxy: listen tcp 0.0.0.0:80: bind: address already in use

Can you help me for a solution?

**Comment by tboerger** [comment]
Sorry, but the error already tells you everything you need, port 80 is already used on your host.

**Comment by amaurybsouza** [comment]
Thanks @tboerger
