### ISSUE TITLE
Contribution Guidelines - Pull Requests

### ISSUE THREAD

**Issue by ThomDietrich** [owncloud-docker/server#152]
Hello @tboerger,

thanks for providing and maintaining this solution. Doing this voluntary aside other things is no easy task and you have my respect for it.

That said, I'd like to take this [step](https://github.com/owncloud-docker/server/commit/71369eadbb3521930c2eca116f8e2acd657b692a) as an example. I am not here to disagree! I might not be a supporter of the decision, not at all, but I want to discuss another matter.
I would like to highlight the fact that most open source repositories have a "Only pull requests" policy for good reason. Every change should come through a pull request to allow visibility and inclusion of other community members. This does not exclude the maintainer. One could just as well create a PR and merge it directly. The important detail here is, I and everyone else "watch"ing this repo will be notified by GitHub and if need be a discussion can be held.

Transparency is very important nowadays.

I am most interested in your feedback. Thanks and Best!

**Comment by tboerger** [comment]
You are totally right, it should always get through pull requests. So far it should be done like that most of the time, but sometimes I forgot to check if I'm on the right branch and I've got git aliases that commit and push changes.

So it's more like an accident if something gets pushed to the master branch without a PR.

I will push myself even more info that direction to make sure you won't miss changes anymore :)

**Comment by ThomDietrich** [comment]
Amazing. Thank you! ;)
