### ISSUE TITLE
How do I configure for large files?

### ISSUE THREAD

**Issue by aratar79** [owncloud-docker/server#155]
I can't upload files larger than a few mega bytes, I try to follow the documentation settings for large files but it doesn't work. I'm using jwilder nginex reverse proxy container. Have I changed the settings of php.ini, .user.ini and .httpacces any suggestions? Thank you.

**Comment by tboerger** [comment]
The container is working totally fine for large files, maybe you are just running into the same as https://github.com/owncloud-docker/server/issues/154
