### ISSUE TITLE
Cannot login after using OWNCLOUD_SUB_URL

### ISSUE THREAD

**Issue by wolftobias** [owncloud-docker/server#160]
When I use OWNCLOUD_SUB_URL I got the owncloud landing page, but I can`t login with the configured credentials "admin/admin". When I removed OWNCLOUD_SUB_URL and recreate a docker container everthing works!

docker run --name owncloud
-e OWNCLOUD_ADMIN_USERNAME=admin
-e OWNCLOUD_ADMIN_PASSWORD=admin
-e OWNCLOUD_DB_TYPE=mysql
-e OWNCLOUD_DB_NAME=owncloud_db
-e OWNCLOUD_DB_USERNAME=xxx
-e OWNCLOUD_DB_PASSWORD=xxx
-e OWNCLOUD_DB_HOST=xxx
-e OWNCLOUD_SUB_URL=/owncloud/
-d -p 8082:8080 owncloud/server

**Comment by michaelstingl** [comment]
This comes from the base image/repo:
https://github.com/owncloud-docker/base/search?q=OWNCLOUD_SUB_URL

**Comment by michaelstingl** [comment]
@wolftobias anything suspicious in the logs?

**Comment by wolftobias** [comment]
Problem disappear for unknown reason. I removed the docker container and re-run it the next day. Now it works. THX for your support.
