### ISSUE TITLE
Cron integration broken in owncloud/server:10.3.0 docker image

### ISSUE THREAD

**Issue by jperville** [owncloud-docker/server#161]
After migrating a legacy package-based deployment of owncloud to the owncloud/server:10.3.0 docker image, I noticed that the cronjob integration is broken.

# Symptom

In the general settings of admin user, there is a warning about cron job not having run for a while.

# Investigation

Inside the docker image, the /etc/cron.d/owncloud file is present, however it does not execute properly if I manually run it as www-data user ; moving a specific file out of the way seems to workaround the issue.

# Reproduction

In a first terminal, run:
```sh
$ docker run --rm -ti --name=owncloud -p 8080:8080 docker.io/owncloud/server:10.3.0
```

In another terminal, run:
```sh
$ docker exec -ti owncloud /bin/bash                              

root# ls /etc/cron.d
owncloud  php

root# ls -l /etc/cron.d
total 8
-rw-r--r-- 1 root root  38 Oct 28 08:48 owncloud
-rw-r--r-- 1 root root 712 Oct 28 08:48 php

root# cat /etc/cron.d/owncloud 
*/1 * * * * www-data /usr/bin/cronjob

root# su-exec www-data /usr/bin/cronjob
/etc/entrypoint.d/98-overwrite.sh: line 12: /etc/environment: Permission denied
```

Here we have the bug. The reason is that the /etc/entrypoint.d/98-overwrite.sh in the docker image is sourced when executing the cronjob as www-data and that script has a line which tries to overwrite the /etc/environment file. When running as non-root, the permission to overwrite this file is (rightly) refused by the OS.

```sh
$ docker exec -ti owncloud cat /etc/entrypoint.d/98-overwrite.sh
#!/usr/bin/env bash

export HOME="${HOME:-/var/www/owncloud}"
export LANG="${LANG:-C}"

export APACHE_ERROR_LOG="${OWNCLOUD_ERRORLOG_LOCATION:-/dev/stderr}"
export APACHE_ACCESS_LOG="${OWNCLOUD_ACCESSLOG_LOCATION:-/dev/stdout}"
export APACHE_DOCUMENT_ROOT="${APACHE_DOCUMENT_ROOT:-/var/www/owncloud}"
export APACHE_LISTEN="${APACHE_LISTEN:-8080}"

# Write env to file for crond
env >| /etc/environment

true
```

# Workaround

The workaround I did was to `mv /etc/entrypoint.d/98-overwrite.sh` out of the way.
A better fix would be to make this file source safely with non-root user (eg. exit early if `$UID != 0`).

**Comment by tboerger** [comment]
I have prepared a PR to the base image to fix the cronjob in general.

**Comment by jperville** [comment]
Thanks for the PR @tboerger . I tried different versions of the owncloud/server docker image and I found that this bug with the cronjob is present since owncloud 10.x (not present in owncloud 9.x and earlier).

**Comment by tboerger** [comment]
I can't confirm that... I can just confirm that 10.3.x is broken, I just tried out 10.2.0 and there the cronjob is executing totally fine.
