### ISSUE TITLE
Error during transfer, sql duplicate entry

### ISSUE THREAD

**Issue by ThomDietrich** [owncloud-docker/server#17]
Hey guys, not sure if this is directly related to this project but I did never see the issue before with natively installed packages.
I'm in the process to upload 100GB of files and am occasionally seeing the following error in the desktop sync client.

```
Error transferring https://xxx.tld/remote.php/dav/files/th/Fotos/DCIM/2016/2016-01-01_19.59.52.jpg - server replied: Internal Server Error (An exception occurred while executing 'INSERT INTO `oc_filecache` (`mimepart`,`mimetype`,`mtime`,`size`,`etag`,`storage_mtime`,`permissions`,`checksum`,`parent`,`path_hash`,`path`,`name`,`storage`) SELECT ?,?,?,?,?,?,?,?,?,?,?,?,? FROM `oc_filecache` WHERE `storage` = ? AND `path_hash` = ? HAVING COUNT(*) = 0' with params ["1", "2", 1500547390, -1, "5970893eda4cc", 1500547390, 31, "", 360243, "2624f7444256c086dac0fb12be623c91", "files_encryption\/keys\/files\/Fotos\/DCIM\/2016", "2016", 4, 4, "2624f7444256c086dac0fb12be623c91"]:

SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '4-2624f7444256c086dac0fb12be623c91' for key 'fs_storage_path_hash')
```

Any idea what's going on here and if I need to concern myself with it?

Edit: by now I can confirm, that the files are successfully transferred at the next sync run.

**Comment by tboerger** [comment]
That sounds more like a core issue. Maybe @PVince81 or @DeepDiver1975 got an idea.

**Comment by tboerger** [comment]
After talking to the team it should be a core issue, please open an issue at https://github.com/owncloud/core.
