### ISSUE TITLE
Question: how to restart apache within the container?

### ISSUE THREAD

**Issue by rdkgit** [owncloud-docker/server#171]

**Comment by rdkgit** [comment]
Hey!  This is a question, not an issue.

I edited config.php to set trusted domains.

How does one re-start apache2 within the container?  When I try to do so, I get this error:

ERROR: APACHE_PID_FILE needs to be defined in /etc/apache2/envvars

Thanks,

Bobby

**Comment by tboerger** [comment]
For changing config.php the webserver doesn'T have to be restarted. Beside that a command similar to this COULD work: `docker exec owncloud entrypoint apachectl restart`

**Comment by rdkgit** [comment]
Thank you.
