### ISSUE TITLE
does not work with arm32v7

### ISSUE THREAD

**Issue by soydepr** [owncloud-docker/server#172]
Does not work with arm32v7  and documentation does not specifies this

**Comment by tboerger** [comment]
Without providing more details nobody will be able to help you.

**Comment by soydepr** [comment]
getting this error 

pi@lucas:~/owncloud-docker-server $ docker-compose up -d
Unable to find image 'docker/compose:1.25.4' locally
1.25.4: Pulling from docker/compose
89d9c30c1d48: Pull complete 
eccc02a3b135: Pull complete 
7382d3c5d78f: Pull complete 
f410c750fbcb: Pull complete 
Digest: sha256:390bdf3da99a622f5c11f4db386dd97f2858db30cfed07d000b867f1fb25b2f7
Status: Downloaded newer image for docker/compose:1.25.4
standard_init_linux.go:211: exec user process caused "exec format error"

**Comment by tboerger** [comment]
This issue seem to be related to docker/compose:1.25.4, why do you think the the owncloud docker image doesn't work?

**Comment by soydepr** [comment]
because it does not load i tried a few workarounds ns that got compose to load but owncloud didint load 

question is does it support arm32v7?

**Comment by tboerger** [comment]
arm32v7 should be supported for our docker image. I think rpi4 should be arm64v8.

**Comment by soydepr** [comment]
i see what you mean but perhaps docker-compose is not so how can i get this running without docker compose

**Comment by soydepr** [comment]
was able to get running from container, how do i access the config file

**Comment by tboerger** [comment]
The issue tracker is not meant to be a support portal, you should follow https://doc.owncloud.com/server/10.4/admin_manual/installation/docker/ which includes all required information. Beside that you should just look into the volume mounted by the container. For further help please open a thread on https://central.owncloud.org/.
