### ISSUE TITLE
Information icon for new version leads to wrong port

### ISSUE THREAD

**Issue by lex2k0** [owncloud-docker/server#174]
When I log in to my owncloud in the browser for updating any extensions I see an information icon on top of owncloud.
Clicking that leads to a wrong address. It is ignoring the current address and leads to port the default address.
This seems to be fine for non-docker versions but in my case I am using docker together with traefik thus I am able to use ssl and so on.
All is working fine but not for updates.

Expected behavior would be that also those information links are working properly,

**Comment by tboerger** [comment]
If you are providing all the environment variables like `OWNCLOUD_DOMAIN` and `OWNCLOUD_PROTOCOL`  these links are getting generated correctly. Note: Applying these env variables afterwards won't update already existing notifications, this will only apply to future notifications.

**Comment by lex2k0** [comment]
Ok, thanks @tboerger.
Domain ist set and working, that is not the problem. But would the protocol work as owncloud is running in a docker with traefik?
And what about the port, because that one is set to 80 instead of the correct port and I am not able to find an environmental variable setting the port for owncloud in docker?

Kind regards

**Comment by lex2k0** [comment]
Hello again,

maybe someone could help me regarding this?
Still not able to find the solution for the port. OWNCLOUD_DOMAIN and OWNCLOUD_PROTOCOL is set, but the port is not 8080 as I am using traefik on a different https-Port.

Thanks!

**Comment by lex2k0** [comment]
Hello,

in the meanwhile I could validate that the solution with the OWNCLOUD_PROTOCOL is working and I am seeing https instead of http.
But the port is still not set thus this is still on 8080. Is there also a variable available where it is somehow possible to change that port?

Thanks!

**Comment by lex2k0** [comment]
Hello,

for all who have the same problem. In the meanwhile I found the solution.
Use `OWNCLOUD_PROTOCOL` to use https and USE `OWNCLOUD_DOMAIN` to not only set the domain but also set the port like owncloud.test.net:12345.
With those settings the docker version of owncloud is creating the `overwrite.cli.url` setting in the config.php like https://owncloud.text.net:12345.

Thanks a lot for your help!
