### ISSUE TITLE
Is there a way to lift the "file name too long" restriction?

### ISSUE THREAD

**Issue by dznas** [owncloud-docker/server#175]
In my scenario, some file names need to be long, but they ca n’t be uploaded
"File name is too long" and "Could not write file contents"
I am a Chinese user，Chinese takes more characters
Is it possible to modify this restriction

10.3.2
I tried google but no answer
thank you for the help

**Comment by tboerger** [comment]
This is not related to the docker image at all. You should ask something like that on https://central.owncloud.org.
