### ISSUE TITLE
ssl problem and not login new user

### ISSUE THREAD

**Issue by darkban** [owncloud-docker/server#176]
on my vps i have two different docke start the first perfectly working also on ssl the second (owncloud) i used this guide

https://doc.owncloud.com/server/admin_manual/installation/docker/

everything works but only on port 8080 I would like it to always work on that port but with https how can I do? what commands do i have to launch so as not to conflict the two dockers?

then there is a strange problem when I create a user and check user and password and then I try to access it from another browser it does not let me log in as if the password was wrong but in realization it is not how to solve these two problems?

**Comment by tboerger** [comment]
For enabling SSL termination for multiple services you got to use a reverse proxy like [Traefik](https://docs.traefik.io/) or [nginx-proxy](https://github.com/nginx-proxy/nginx-proxy), this is  not handled by the ownCloud container.

**Comment by darkban** [comment]
and i can enable also in port 8080 or force used 443?

**Comment by tboerger** [comment]
Just keep the owncloud container on port 8080 and let the reverse proxy handle port 443.
