### ISSUE TITLE
problem new user access

### ISSUE THREAD

**Issue by darkban** [owncloud-docker/server#177]
in http with port 8080 if you create a new user and then try to log in do not log in as if you were wrong password but in reality it is not ... what can it be?

{"ReqId": "zaLU9sjEPhXtTqceqoQS", "level": 2, "time": "2020-03-16T16: 23: 38 + 00: 00", "remoteAddr": "81.112.22.158", "user": " - "," app ":" core "," method ":" POST "," url ":" \ / login "," message ":" Login failed: 'tiziano' (Remote IP: '81 .112.22.158 ' ) "}

**Comment by ThomDietrich** [comment]
Your problem is not clearly stated. This is probably not related to docker. Please the internet for your problem and write a proper support post on the docker forum

**Comment by darkban** [comment]
the problem is this:
when creating a user and assigning a password the user cannot log in I have also seen on google and many have had the same problem with owncloud but no one has been able to solve

**Comment by tboerger** [comment]
Without more details nobody is able to reproduce that for further debugging. That way you can't get help.

I have no idea when this should happen.

**Comment by jnweiger** [comment]
@darkban I've just tested this with a 10.5.0 server. after creating the user, The admin sees that there is a password automatically set, but we cannot get the passwowd from the web interface. As admin, I edit the password, log out, re-log in with the new user, and the newly set password. Works just fine. Closing for now.

Please re-open, if you do it differently and it still fails for you.
