### ISSUE TITLE
Trackability, Update Notifications

### ISSUE THREAD

**Issue by ThomDietrich** [owncloud-docker/server#19]
Hey,
it would be interesting to get notified in case of a new image version. For me personally either via GitHub notifications or as an RSS feed are fine.

Currently there is only https://github.com/owncloud-docker/server/commits/master.atom

If the project would be managed with git tags and GitHub Releases, every potential user could subscribe to notifications either ways. Additionally the GitHub release would be the right place for changelog information, currently missing.

Wdyt?

**Comment by tboerger** [comment]
Totally makes sense, need to discuss a proper way we want to go for that.

**Comment by ThomDietrich** [comment]
Any news on this front?

**Comment by tboerger** [comment]
Nothing provided in the direction yet

**Comment by ThomDietrich** [comment]
I know :) Just asking if you are going to. Creating a tag+release every time anew owncloud version is provided shouldn't be any serious extra work and would go a long way in terms of ease-of-use...

**Comment by tboerger** [comment]
I will close this issue for now, all changes are happening within the base image and you can track the changes via the changelog:

* https://github.com/owncloud-docker/base/blob/master/CHANGELOG.md
* https://github.com/owncloud-docker/base/blob/xenial/CHANGELOG.md
* https://github.com/owncloud-docker/base/blob/bionic/CHANGELOG.md

If you directly want to track the builds you can track https://drone.owncloud.com/owncloud-docker/server.
