### ISSUE TITLE
remove updater app

### ISSUE THREAD

**Issue by voroyam** [owncloud-docker/server#20]
update should never be made via the updater app using docker image

**Comment by voroyam** [comment]
fixes https://github.com/owncloud/appliance/issues/32

**Comment by voroyam** [comment]
@tboerger ping

**Comment by tboerger** [comment]
If somebody can tell me what needs to be disabled and uninstalled I can integrate that.

**Comment by tboerger** [comment]
Solved via 01e31cd

**Comment by michaelstingl** [comment]
@tboerger Updater came back:

<img width="804" alt="settings_-_owncloud" src="https://user-images.githubusercontent.com/214010/35747538-e6b14e96-084a-11e8-86d2-1a6c7c9952e2.png">

Steps to reproduce:

1. `$ git clone git@github.com:owncloud-docker/server.git`
2. `$ cd server/`
3. `$ nano .env` ==> change to `VERSION=10.0.4`
4.  `$ docker-compose up -d`

**Comment by tboerger** [comment]
Looks like aou are not using the latest version of the image. I have added https://github.com/owncloud-docker/base/commit/01e31cdb57631a20cf8a809aa8422afd44cde1b0 and later on also https://github.com/owncloud-docker/base/commit/4ea0b3881f13ccdf022222cbf0ebebbc2757cead which seems to be the only stuff I can do from my side. This results in a still visible updater section, but it doesn't show an available update:

<img width="822" alt="bildschirmfoto 2018-02-05 um 13 07 28" src="https://user-images.githubusercontent.com/156964/35803883-b7e09216-0a75-11e8-9544-33a974269cd4.png">

If core provides better options to disable it feel free to provide a PR or to reopen the issue. For the meantime I have applied all options I've got.

**Comment by michaelstingl** [comment]
@PVince81 @pmaier1 Looks like we need a config option to prevent an app getting activated ALWAYS. Any idea?

**Comment by PVince81** [comment]
I guess it's probably not this one https://github.com/owncloud/core/blob/v10.0.6/config/config.sample.php#L1397

@VicDeo didn't we have an option already ?

From what I remember, there was a time where we stripped out the updater from the tarballs in distro packages, but I suspect that we might have added it back as it would likely violate the integrity check

**Comment by VicDeo** [comment]
> I guess it's probably not this one https://github.com/owncloud/core/blob/v10.0.6/config/config.sample.php#L1397

You're correct `'upgrade.disable-web'` is about upgrade process not about notification

this way
https://github.com/owncloud/core/blob/v10.0.6/config/config.sample.php#L546

**Comment by michaelstingl** [comment]
Hm, it seems I had some old images/containers whatever running… Fixed it.

This parameters are in my config.php:

```
  'updatechecker' => 'false',
  'upgrade.disable-web' => true,
```

Updater app showing "**Your version is up to date.**" looks confusing on a 10.0.4 ownCloud.

Do we need an adjustment in the updater app to display something more useful if those parameters are set?

Or build a config option/mechanism to prevent an app getting activated?

**Comment by tboerger** [comment]
> Do we need an adjustment in the updater app to display something more useful if those parameters are set?

This should be one way, or just provide a flag that hides the updater stuff entirely. If something like that comes up within the core I will directly add it to the docker images. After that we will have the same for our appliance.

**Comment by pmaier1** [comment]
I would be fine with just displaying "The web updater is disabled." if those config.php settings are set. It would of course be more clean to be able to hide the section. Would leave that up to you depending on effort.
