### ISSUE TITLE
Arm support

### ISSUE THREAD

**Issue by matthieudelaro** [owncloud-docker/server#21]
Hi,

thanks for those images. Would it be possible to have an arm version (for raspi)  ?

Thanks,

**Comment by tboerger** [comment]
I would like to provide ARM images, but the Docker Hub doesn't provide this functionality and our own build infrastructure currently don't include ARM servers.

**Comment by tboerger** [comment]
This is nothing we are focusing in the nearby future, if we get back to that I will reopen this issue.
