### ISSUE TITLE
Can i run a application in owncloud using docker

### ISSUE THREAD

**Issue by sabarishsubramanian** [owncloud-docker/server#210]
i want to test a load balancing between cpu and cloud.

so i intsalled owncloud for my cloud.

Now can i run it in docker if so how can i do?

How can i run a application in own cloud.

Kindly help me.

THank you

**Comment by xoxys** [comment]
[ownCloud](https://owncloud.com/product/) is a file sync, share and content collaboration software. You can not run applications in ownCloud.
