### ISSUE TITLE
Can't update /var/www/owncloud/.htaccess

### ISSUE THREAD

**Issue by yg382** [owncloud-docker/server#213]
Hi

I am using this template https://github.com/owncloud-docker/openshift/blob/master/persistent.json but cannot start owncloud due to Can't update /var/www/owncloud/.htaccess

Any idea how to solve this issue 
[ansible@dh-ansible ~]$ oc logs -f owncloud-4-qbtxv
Creating volume folders...
Creating hook folders...
Waiting for MySQL...
services are ready!
Waiting for Redis...
services are ready!
Removing custom folder...
Linking custom folder...
Removing config folder...
Linking config folder...
Writing config file...
Skipping chown as requested...
Fixing hook perms...
Upgrading server database...
ownCloud is already latest version
ownCloud is already latest version
Writing objectstore config...
Writing php config...
Updating htaccess config...

In Setup.php line 522:

  Can't update /var/www/owncloud/.htaccess

maintenance:update:htaccess

**Comment by bcr-ch** [comment]
I also have this issue, 

My YAML extract for creating the container:

`spec:
      hostname: owncloud
      serviceAccount: owncloud
      containers:
      - name: owncloud
        image: owncloud/server
        imagePullPolicy: IfNotPresent
        systemd: false
        env:
        - name: OWNCLOUD_ADMIN_USERNAME
          value: REMOVED
        - name: OWNCLOUD_DOMAIN
          value: REMOVED
        - name: OWNCLOUD_DB_TYPE
          value: mysql
        - name: OWNCLOUD_DB_NAME
          value: owncloud
        - name: OWNCLOUD_DB_HOST
          value: owncloud-db
        - name: OWNCLOUD_MYSQL_UTF8MB4
          value: "true"
        - name: OWNCLOUD_REDIS_ENABLED
          value: "yes"
        - name: OWNCLOUD_REDIS_HOST
          value: owncloud-redis
        - name: OWNCLOUD_REDIS_PORT
          value: "6379"
        - name: OWNCLOUD_SESSION_SAVE_HANDLER
          value: redis
        - name: OWNCLOUD_SESSION_SAVE_PATH
          value: "tcp://owncloud-redis:6379?database=1"
        - name: OWNCLOUD_SKIP_CHOWN
          value: "true"
        - name: OWNCLOUD_VOLUME_ROOT
          value: /mnt/data
        envFrom:
        - secretRef:
            name: owncloud-secret
        ports:
          - name: http
            containerPort: 8080
            protocol: TCP
        volumeMounts:
        - name: server-storage
          mountPath: /mnt/data/
      volumes:
      - name: server-storage
        persistentVolumeClaim:
          claimName: owncloud-file-storage-claim
      securityContext:
        allowPrivilegeEscalation: false`
