### ISSUE TITLE
failed to install with docker

### ISSUE THREAD

**Issue by stlnkm** [owncloud-docker/server#23]
I failed to install owncloud docker with latest webhippie/mariadb docker and latest webhippie/resdist docker on centos 7，I had try several newest versions of owncloud，include 10.0.3。 Any helps are welcome! Thanks in advance!

> owncloud_1  | Creating volume folders...
owncloud_1  | Waiting for MySQL...
owncloud_1  | wait-for-it: waiting 180 seconds for db:3306
owncloud_1  | wait-for-it: db:3306 is available after 13 seconds
owncloud_1  | Removing custom folder...
owncloud_1  | Linking custom folder...
owncloud_1  | Removing config folder...
owncloud_1  | Linking config folder...
owncloud_1  | Copying config file...
owncloud_1  | Copying domains file...
owncloud_1  | Copying db file...
owncloud_1  | Copying utf8mb4 config...
owncloud_1  | Fixing base perms...
owncloud_1  | Fixing data perms...
owncloud_1  | Installing server database...
owncloud_1  | ownCloud is not installed - only a limited number of commands are available
owncloud_1  | Error while trying to create admin user: An exception occurred while executing 'SELECT COLUMN_NAME AS Field, COLUMN_TYPE AS Type, IS_NULLABLE AS `Null`, COLUMN_KEY AS `Key`, COLUMN_DEFAULT AS `Default`, EXTRA AS Extra, COLUMN_COMMENT AS Comment, CHARACTER_SET_NAME AS CharacterSet, COLLATION_NAME AS Collation FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = 'owncloud' AND TABLE_NAME = 'oc_appconfig'':
owncloud_1  |
owncloud_1  | SQLSTATE[HY000]: General error: 1036 Table '/tmp/#sql_129_0.MAI' is read only
owncloud_1  |  ->
owncloud_1  |
owncloud_1  |
owncloud_1  |   [Symfony\Component\Console\Exception\CommandNotFoundException]
owncloud_1  |   There are no commands defined in the "config:system" namespace.
owncloud_1  |
owncloud_1  |
owncloud_1  | dpkg: error: --compare-versions takes three arguments: <version> <relation> <version>
owncloud_1  |
owncloud_1  | Type dpkg --help for help about installing and deinstalling packages [*];
owncloud_1  | Use 'apt' or 'aptitude' for user-friendly package management;
owncloud_1  | Type dpkg -Dhelp for a list of dpkg debug flag values;
owncloud_1  | Type dpkg --force-help for a list of forcing options;
owncloud_1  | Type dpkg-deb --help for help about manipulating *.deb files;
owncloud_1  |
owncloud_1  | Options marked [*] produce a lot of output - pipe it through 'less' or 'more' !
owncloud_1  | Enabling files_external app...
owncloud_1  |
owncloud_1  |
owncloud_1  |   [Symfony\Component\Console\Exception\CommandNotFoundException]
owncloud_1  |   There are no commands defined in the "config:system" namespace.
owncloud_1  |
owncloud_1  |
owncloud_1  | dpkg: error: --compare-versions takes three arguments: <version> <relation> <version>
owncloud_1  |
owncloud_1  | Type dpkg --help for help about installing and deinstalling packages [*];
owncloud_1  | Use 'apt' or 'aptitude' for user-friendly package management;
owncloud_1  | Type dpkg -Dhelp for a list of dpkg debug flag values;
owncloud_1  | Type dpkg --force-help for a list of forcing options;
owncloud_1  | Type dpkg-deb --help for help about manipulating *.deb files;
owncloud_1  |
owncloud_1  | Options marked [*] produce a lot of output - pipe it through 'less' or 'more' !
owncloud_1  | Generating default cert...
owncloud_1  | Generating a 4096 bit RSA private key
owncloud_1  | .................................................++
owncloud_1  | ......................++
owncloud_1  | writing new private key to '/mnt/data/certs/ssl-cert.key'
owncloud_1  | -----
owncloud_1  | Enforcing cli url...
owncloud_1  | ownCloud is not installed - only a limited number of commands are available
owncloud_1  |
owncloud_1  |
owncloud_1  |   [Symfony\Component\Console\Exception\CommandNotFoundException]
owncloud_1  |   There are no commands defined in the "config:system" namespace.
owncloud_1  |
owncloud_1  |
owncloud_1  | Disabling update checks...
owncloud_1  | ownCloud is not installed - only a limited number of commands are available
owncloud_1  |
owncloud_1  |
owncloud_1  |   [Symfony\Component\Console\Exception\CommandNotFoundException]
owncloud_1  |   There are no commands defined in the "config:system" namespace.
owncloud_1  |
owncloud_1  |
owncloud_1  | Disabling memcached config...
owncloud_1  | ownCloud is not installed - only a limited number of commands are available
owncloud_1  |
owncloud_1  |
owncloud_1  |   [Symfony\Component\Console\Exception\CommandNotFoundException]
owncloud_1  |   There are no commands defined in the "config:system" namespace.
owncloud_1  |
owncloud_1  |
owncloud_1  | ownCloud is not installed - only a limited number of commands are available
owncloud_1  |
owncloud_1  |
owncloud_1  |   [Symfony\Component\Console\Exception\CommandNotFoundException]
owncloud_1  |   There are no commands defined in the "config:system" namespace.
owncloud_1  |
owncloud_1  |
owncloud_1  | ownCloud is not installed - only a limited number of commands are available
owncloud_1  |
owncloud_1  |
owncloud_1  |   [Symfony\Component\Console\Exception\CommandNotFoundException]
owncloud_1  |   There are no commands defined in the "config:system" namespace.
owncloud_1  |
owncloud_1  |
owncloud_1  | Waiting for Redis...
owncloud_1  | wait-for-it: waiting 60 seconds for redis:6379
owncloud_1  | wait-for-it: redis:6379 is available after 0 seconds
owncloud_1  | Enabling redis config...
owncloud_1  | ownCloud is not installed - only a limited number of commands are available
owncloud_1  |
owncloud_1  |
owncloud_1  |   [Symfony\Component\Console\Exception\CommandNotFoundException]
owncloud_1  |   There are no commands defined in the "config:system" namespace.
owncloud_1  |
owncloud_1  |
owncloud_1  | ownCloud is not installed - only a limited number of commands are available
owncloud_1  |
owncloud_1  |
owncloud_1  |   [Symfony\Component\Console\Exception\CommandNotFoundException]
owncloud_1  |   There are no commands defined in the "config:system" namespace.
owncloud_1  |
owncloud_1  |
owncloud_1  | ownCloud is not installed - only a limited number of commands are available
owncloud_1  |
owncloud_1  |
owncloud_1  |   [Symfony\Component\Console\Exception\CommandNotFoundException]
owncloud_1  |   There are no commands defined in the "config:system" namespace.
owncloud_1  |
owncloud_1  |
owncloud_1  | Disabling file locking...
owncloud_1  | ownCloud is not installed - only a limited number of commands are available
owncloud_1  |
owncloud_1  |
owncloud_1  |   [Symfony\Component\Console\Exception\CommandNotFoundException]
owncloud_1  |   There are no commands defined in the "config:system" namespace.
owncloud_1  |
owncloud_1  |
owncloud_1  | Configure locale caching...
owncloud_1  | ownCloud is not installed - only a limited number of commands are available
owncloud_1  |
owncloud_1  |
owncloud_1  |   [Symfony\Component\Console\Exception\CommandNotFoundException]
owncloud_1  |   There are no commands defined in the "config:system" namespace.
owncloud_1  |
owncloud_1  |
owncloud_1  | Touching log file...
owncloud_1  | Setting log level...
owncloud_1  | ownCloud is not installed - only a limited number of commands are available
owncloud_1  |
owncloud_1  |
owncloud_1  |   [Symfony\Component\Console\Exception\CommandNotFoundException]
owncloud_1  |   There are no commands defined in the "config:system" namespace.
owncloud_1  |
owncloud_1  |
owncloud_1  | Setting default language...
owncloud_1  | ownCloud is not installed - only a limited number of commands are available
owncloud_1  |
owncloud_1  |
owncloud_1  |   [Symfony\Component\Console\Exception\CommandNotFoundException]
owncloud_1  |   There are no commands defined in the "config:system" namespace.
owncloud_1  |
owncloud_1  |
owncloud_1  | Enabling background cron...
owncloud_1  | ownCloud is not installed - only a limited number of commands are available
owncloud_1  |
owncloud_1  |
owncloud_1  |   [Symfony\Component\Console\Exception\CommandNotFoundException]
owncloud_1  |   There are no commands defined in the "background" namespace.
owncloud_1  |
owncloud_1  |
owncloud_1  | Removing object storage...
owncloud_1  | Disabling object storage...
owncloud_1  | ownCloud is not installed - only a limited number of commands are available
owncloud_1  |
owncloud_1  |
owncloud_1  |   [Symfony\Component\Console\Exception\CommandNotFoundException]
owncloud_1  |   There are no commands defined in the "config:system" namespace.
owncloud_1  |
owncloud_1  |
owncloud_1  | Setting rewrite base...
owncloud_1  | ownCloud is not installed - only a limited number of commands are available
owncloud_1  |
owncloud_1  |
owncloud_1  |   [Symfony\Component\Console\Exception\CommandNotFoundException]
owncloud_1  |   There are no commands defined in the "config:system" namespace.
owncloud_1  |
owncloud_1  |
owncloud_1  | ownCloud is not installed - only a limited number of commands are available
owncloud_1  |
owncloud_1  |
owncloud_1  |   [Symfony\Component\Console\Exception\CommandNotFoundException]
owncloud_1  |   There are no commands defined in the "maintenance:update" namespace.
owncloud_1  |   Did you mean this?
owncloud_1  |       maintenance
owncloud_1  |
owncloud_1  |
owncloud_1  | Writing apache config...
owncloud_1  | Writing php config...
owncloud_1  | Starting cron daemon...
owncloud_1  | Starting apache daemon...
owncloud_1  | Finishing ownCloud launch...
owncloud_1  | [Sun Nov 05 04:46:41.334311 2017] [ssl:warn] [pid 338] AH01906: localhost:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
owncloud_1  | [Sun Nov 05 04:46:41.395153 2017] [ssl:warn] [pid 339] AH01906: localhost:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
owncloud_1  | [Sun Nov 05 04:46:41.407237 2017] [mpm_prefork:notice] [pid 339] AH00163: Apache/2.4.18 (Ubuntu) OpenSSL/1.0.2g configured -- resuming normal operations
owncloud_1  | [Sun Nov 05 04:46:41.407272 2017] [core:notice] [pid 339] AH00094: Command line: '/usr/sbin/apache2'
owncloud_1  | 127.0.0.1 - - [05/Nov/2017:04:46:53 +0000] "GET /status.php HTTP/1.1" 302 762 "-" "curl/7.47.0"
owncloud_1  | 127.0.0.1 - - [05/Nov/2017:04:47:23 +0000] "GET /status.php HTTP/1.1" 302 764 "-" "curl/7.47.0"
owncloud_1  | 127.0.0.1 - - [05/Nov/2017:04:47:53 +0000] "GET /status.php HTTP/1.1" 302 762 "-" "curl/7.47.0"
owncloud_1  | 127.0.0.1 - - [05/Nov/2017:04:48:23 +0000] "GET /status.php HTTP/1.1" 302 762 "-" "curl/7.47.0"
owncloud_1  | 127.0.0.1 - - [05/Nov/2017:04:48:53 +0000] "GET /status.php HTTP/1.1" 302 768 "-" "curl/7.47.0"
owncloud_1  | 127.0.0.1 - - [05/Nov/2017:04:49:23 +0000] "GET /status.php HTTP/1.1" 302 764 "-" "curl/7.47.0"
owncloud_1  | 127.0.0.1 - - [05/Nov/2017:04:49:53 +0000] "GET /status.php HTTP/1.1" 302 762 "-" "curl/7.47.0"
owncloud_1  | 127.0.0.1 - - [05/Nov/2017:04:50:23 +0000] "GET /status.php HTTP/1.1" 302 766 "-" "curl/7.47.0"
owncloud_1  | 127.0.0.1 - - [05/Nov/2017:04:50:53 +0000] "GET /status.php HTTP/1.1" 302 760 "-" "curl/7.47.0"
owncloud_1  | 127.0.0.1 - - [05/Nov/2017:04:51:24 +0000] "GET /status.php HTTP/1.1" 302 762 "-" "curl/7.47.0"
owncloud_1  | 127.0.0.1 - - [05/Nov/2017:04:51:54 +0000] "GET /status.php HTTP/1.1" 302 770 "-" "curl/7.47.0"
owncloud_1  | 127.0.0.1 - - [05/Nov/2017:04:52:24 +0000] "GET /status.php HTTP/1.1" 302 758 "-" "curl/7.47.0"
owncloud_1  | 127.0.0.1 - - [05/Nov/2017:04:52:54 +0000] "GET /status.php HTTP/1.1" 302 772 "-" "curl/7.47.0"

**Comment by tboerger** [comment]
Please try to add :z at the end of every volume within the docker-compose.yml, it's possible that this is related to selinux.

**Comment by stlnkm** [comment]
@tboerger Thanks for your advice. Selinux is disabled on the docker host, and I add :z to the end of every volumes, but still failed with same error and exception.

> \- ./data:/mnt/data:z
\- ./mysql:/var/lib/mysql:z
\- ./redis:/var/lib/redis:z

> total 16
drwxr-xr-x 7   33   33 4096 Nov  5 21:21 data
-rw-r--r-- 1 root root 1626 Nov  5 20:58 docker-compose.yml
drwxr-xr-x 5 git  git  4096 Nov  5 21:22 mysql
drwxr-xr-x 2  101  102 4096 Nov  5 21:21 redis

Output of "docker-compose ps"
>owncloud_db_1         /usr/bin/entrypoint /bin/s ...   Up      3306/tcp
owncloud_owncloud_1   /usr/local/bin/entrypoint  ...   Up      0.0.0.0:1103->443/tcp, 0.0.0.0:1408->80/tcp
owncloud_redis_1      /usr/bin/entrypoint /bin/s ...   Up      6379/tcp

Dir path is /data/owncloud
> drwxr-xr-x 5 root   root    4096 Nov  5 21:21 owncloud

**Comment by tboerger** [comment]
The error shows that the mariadb container got some problem while writing to disk, feel free to use a different database container or give it another try with a clean database container including the :z option.

**Comment by stlnkm** [comment]
@tboerger Thank you! I change to official mariadb and official redis, instead of webhippie's, and succeeded!

**Comment by tboerger** [comment]
Great that it worked for you
