### ISSUE TITLE
Upgrade from 10.0.2.1 to 10.0.3 not working

### ISSUE THREAD

**Issue by iget-esoares** [owncloud-docker/server#24]
I'm migrating a installation from 10.0.2.1 to 10.0.3 by just swapping owncloud version on .env then recreating the docker-compose project (down then up), but when I run `occ upgrade` I get the following error message:

```
2017-11-07T03:16:03+00:00 Updating database schema
2017-11-07T03:16:03+00:00 Doctrine\DBAL\Schema\SchemaException: There is no table with name 'owncloud.oc_account_terms' in the schema.
2017-11-07T03:16:03+00:00 Update failed
```

Am I doing something wrong or is this broken?

**Comment by tboerger** [comment]
An upgrade gets done automatically at start. If this upgrade fails it sounds like an upstream (core repo) issue.

**Comment by tboerger** [comment]
I'm not able to reproduce it, if the issue still exists please check the upstream repo or provide further feedback.

**Comment by iget-master** [comment]
I've fixed by manually running the `Version20170516100103` migration:

`occ migrations:execute core Version20170516100103`
