### ISSUE TITLE
Centos 7 error 

### ISSUE THREAD

**Issue by sfmarques** [owncloud-docker/server#26]
When I try to install owncloud server in Centos 7, i get this error (docker logs owncloud server):

> Error while trying to create admin user: An exception occurred while executing 'SELECT COLUMN_NAME AS Field, COLUMN_TYPE AS Type, IS_NULLABLE AS `Null`, COLUMN_KEY AS `Key`, COLUMN_DEFAULT AS `Default`, EXTRA AS Extra, COLUMN_COMMENT AS Comment, CHARACTER_SET_NAME AS CharacterSet, COLLATION_NAME AS Collation FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = 'owncloud' AND TABLE_NAME = 'oc_appconfig'':
> 
> SQLSTATE[HY000]: General error: 1036 Table '/tmp/#sql_12e_0.MAI' is read only

If I install in Ubuntu, it works. This is the same if I use docker-compose. Help please.

Thanks

**Comment by tboerger** [comment]
Sounds like a duplicate of https://github.com/owncloud-docker/server/issues/2. Please retry it with the official mysql or mariadb container.

**Comment by sfmarques** [comment]
You mean #23 ;) 
I have to use mariadb 10.0 version
Thanks

**Comment by tboerger** [comment]
Yes, exactly. Wrong copy and paste :)
