### ISSUE TITLE
Changes for same site cookies in 10.7 / 10.8

### ISSUE THREAD

**Issue by michaelstingl** [owncloud-docker/server#261]
Due to changes regarding same site cookies in 10.7 / 10.8, Docker users are logged-out after OAuth 2.0 authorisation.

10.8 with proper settings in Apache | 10.8 running in Docker
-- | --
<img width="774" alt="CleanShot 2021-09-06 at 12 15 01@2x" src="https://user-images.githubusercontent.com/214010/132201674-2d914fd0-8cc3-40aa-88a7-e365c8e44734.png"> | <img width="771" alt="CleanShot 2021-09-06 at 12 15 31@2x" src="https://user-images.githubusercontent.com/214010/132201746-1312c7d2-19d8-433f-b61c-ccf424c4c184.png">
`/index.php/apps/oauth2/authorization-successful` | redirect to `/login?redirect_url=%252Fapps%252Foauth2%252Fauthorization-successful`

**Comment by wkloucek** [comment]
@michaelstingl could you please provide some more details? I'm running a 10.8 in docker with oauth2 app and don't have any noticeable problems

**Comment by michaelstingl** [comment]
What screen do you see after desktop client authorisation? Left or right one?

**Comment by wkloucek** [comment]
The screen on the left.

https://user-images.githubusercontent.com/34452982/135586638-24765d2d-2706-415a-ab3d-34de16dea250.mp4

**Comment by michaelstingl** [comment]
I tried this:

```
docker pull owncloud/server:latest
docker run --rm -d \              
  --name owncloud \
  -p 18080:8080 \
  -e OWNCLOUD_APPS_ENABLE=oauth2 \
  -e ADMIN_USERNAME=admin \
  -e ADMIN_PASSWORD=admin \
  owncloud/server:latest
```

Then I connected my 2.82 desktop client to http://10.18.17.160:18080/ (2.9 complains about non-SSL connection). After this, I still see the login, as seen in the right image. (Safari 14.0.3 (16610.4.3.1.7) on macOS Big Sur 11.2.3 (20D91))

**Comment by xoxys** [comment]
Please try `OWNCLOUD_HTTP_COOKIE_SAMESITE=None`

**Comment by michaelstingl** [comment]
> Please try `OWNCLOUD_HTTP_COOKIE_SAMESITE=None`

Yes, works 👍

**Comment by michaelstingl** [comment]
`-e OWNCLOUD_HTTP_COOKIE_SAMESITE=lax` works too 👍
