### ISSUE TITLE
docker stop times out

### ISSUE THREAD

**Issue by WenbinHou** [owncloud-docker/server#28]
Hello, I'm facing a problem that I can't (normally) stop the container via `docker stop my-owncloud`.
It just times out (after 10 seconds) and then is killed.
Could you please handle SIGTERM sent by docker, and stops more gracefully?
Thanks a lot.

**Comment by petehalverson** [comment]
The --init flag launches the container as a child process of tini and terminates your process even if you didn't explicitly install a signal handler. This should resolve issues commonly run into when stopping containers. More info: https://github.com/krallin/tini

**Comment by tboerger** [comment]
I will do some refactoring on the docker images soon and I will keep this issue in mind.

**Comment by tboerger** [comment]
This issue have been solved with latest and 10.0.10 tags.
