### ISSUE TITLE
Change config file

### ISSUE THREAD

**Issue by sfmarques** [owncloud-docker/server#29]
Hello,

First of all, i think this is not the same problem as https://github.com/owncloud-docker/server/issues/3. I can change config but when I restart docker container, all changes disappears to default when has installed.

My OS is Centos 7 and my docker:

> Client:
>  Version:      17.09.0-ce
>  API version:  1.32
>  Go version:   go1.8.3
>  Git commit:   afdb6d4
>  Built:        Tue Sep 26 22:42:45 2017
>  OS/Arch:      linux/amd64
> 
> Server:
>  Version:      17.09.0-ce
>  API version:  1.32 (minimum version 1.12)
>  Go version:   go1.8.3
>  Git commit:   afdb6d4
>  Built:        Tue Sep 26 22:41:24 2017
>  OS/Arch:      linux/amd64
>  Experimental: false

I´m not using docker compose.

**Comment by sfmarques** [comment]
Tests I made:

1. I disable SELinux
2. I used :z and :Z
3. I installed in Ubuntu 17.10 like i did on Centos
4. I changed config file inside the container

Nothing works after restarting the container

**Comment by tboerger** [comment]
Please be more precise and tell me what you tried to change.

**Comment by sfmarques** [comment]
First of all I apologize because I can write in the config file, i add 'theme' => 'example', to config.php, restarted the container and it not disappeared. What I can not change and stays is the language, I change to 'default_language' => 'pt_PT', it gets altered in owncloud web gui, but after restart the container, it come back to 'default_language' => 'en'. I added the settings/languageCodes.php file, but even then, every time I restarted the container, I lose my language settings.

**Comment by tboerger** [comment]
You can find a list of available environment variables at https://github.com/owncloud-docker/base#available-environment-variables, the language gets enforced by the env variable `OWNCLOUD_DEFAULT_LANGUAGE`. So if you want to change the default language just run something like `docker run ... -e OWNCLOUD_DEFAULT_LANGUAGE=pt_PT owncloud/server:your-tag`.
