### ISSUE TITLE
Can't write into config directory!

### ISSUE THREAD

**Issue by michaelstingl** [owncloud-docker/server#3]
I use "Manual Startup" method:

```
Michaels-MacBook-Pro:~ mstingl_oc$ docker run -d --name redis -e REDIS_OPTS="--protected-mode no" webhippie/redis:latest
b60e1f23303256717e3769f88d3b077c724655682f64f50ff80e284a17b6473f
Michaels-MacBook-Pro:~ mstingl_oc$ docker run -d --name mariadb -e MARIADB_ROOT_PASSWORD=secret webhippie/mariadb:latest
4ac2ce285684164018ca5ff9d63baf234b19c6b37478fc4630dd9a1f96180817
Michaels-MacBook-Pro:~ mstingl_oc$ docker run -d -ti \
>   --name owncloud \
>   --link mariadb:mariadb --link redis:redis \
>   -p 443:443 \
>   owncloud/server
137347fab60501708ced4a66d8489a1afe79963476daaa6e1ab210bcc1c9526a
Michaels-MacBook-Pro:~ mstingl_oc$ 
```

This result in an error on https://localhost/

```
Can't write into config directory!
This can usually be fixed by giving the webserver write access to the config directory.
```

@felixboehm could you check?

(Docker Version 1.12.0-rc4-beta20 on Mac OS X 10.11.5)

**Comment by felixboehm** [comment]
Starting with docker-compose, default is to mount the `data` Directory.
If you start ownCloud from scratch (down, up), you might forget to delete the old data folder, and mount existing data folder to new ownCloud.

I want to improve detection for existing data directory, while no installation happened.
Added to Todo-List: https://github.com/owncloud-docker/server/issues/1#issuecomment-236641910

**Comment by felixboehm** [comment]
HowTo restart
```bash
docker-compose down
rm -rf ./data
docker-compose up -d
```

**Comment by felixboehm** [comment]
With docker for mac this was an issue with osfs, which is solved on my system with latest docker version.
