### ISSUE TITLE
Placed behind a proxy with custom domain, Logout button is the direct IP

### ISSUE THREAD

**Issue by tebruno99** [owncloud-docker/server#31]
export OWNCLOUD_VERSION=10.0
export OWNCLOUD_DOMAIN=owncloud.myhouse.com
export OWNCLOUD_ADMIN_USERNAME=admin
export OWNCLOUD_ADMIN_PASSWORD=admin
export OWNCLOUD_HTTP_PORT=80
export OWNCLOUD_HTTPS_PORT=443

Everything is working great, login, file transfers, webdav, owncloud client.  Everything except the Logout button which renders itself as "http://192.168.1.50" instead of owncloud.myhouse.com.  All other links, pages, etc all are the correct url "http://owncloud.myhouse.com"

**Comment by tboerger** [comment]
Does your proxy pass the host headers correctly? We go this docker container running at https://demo.owncloud.com behind a reverse proxy that passes the host headers and it's working fine.

**Comment by tebruno99** [comment]
The proxy is nginx and I have the following:

        location / {
                proxy_pass http://192.168.1.50;
                proxy_pass_request_headers on;
        }

Which works for my non-Docker install of ownCloud. All menus and buttons except Logout seem to be working completely fine

**Comment by tebruno99** [comment]
Ok, good call. I had to explicitly set Host header even with proxy_pass_request_headers on

        location / {
                proxy_pass http://192.168.1.50:8880;
                proxy_set_header                Host $host;
                proxy_pass_request_headers on;
        }
