### ISSUE TITLE
Apache missing config variable

### ISSUE THREAD

**Issue by duprasf** [owncloud-docker/server#315]
When I run the command ```apachectl -V``` in the owncloud container, the first three lines shows errors. I'm not an expert in Docker or the Docker image of OwnCloud, so I'm not sure if I missed something or if there is something in the image that could/should be fixed.
```
/etc/apache2 # apachectl -V
[Mon Jun 13 21:01:55.960662 2022] [core:warn] [pid 224] AH00111: Config variable ${APACHE_LOCK_DIR} is not defined
[Mon Jun 13 21:01:55.960771 2022] [core:warn] [pid 224] AH00111: Config variable ${APACHE_RUN_DIR} is not defined
apache2: Syntax error on line 4 of /etc/apache2/apache2.conf: DefaultRuntimeDir must be a valid directory, absolute or relative to ServerRoot
```

**Comment by wkloucek** [comment]
`APACHE_RUN_DIR` is set in https://github.com/owncloud-docker/php/blob/8cea3412019798430694911f969bd77da96b6654/v20.04/overlay/etc/entrypoint.d/99-apache.sh#L15-L16

`APACHE_LOCK_DIR` is set in https://github.com/owncloud-docker/php/blob/8cea3412019798430694911f969bd77da96b6654/v20.04/overlay/etc/entrypoint.d/99-apache.sh#L21-L22

So if you use the default entrypoint / command (https://github.com/owncloud-docker/php/blob/master/v20.04/overlay/usr/bin/server, https://github.com/owncloud-docker/php/blob/master/v20.04/overlay/usr/bin/entrypoint) it's all set up.

If this does not answer your question please reopen
