### ISSUE TITLE
Provide way to customize php.ini for max filesizes

### ISSUE THREAD

**Issue by tebruno99** [owncloud-docker/server#32]
While using the container I've had to go in and modify the php.ini (and possibly apache) files to support larger memory and upload filesizes.  It would be nice if these files could reside along with the rest of the configuration via external mounts so that on updates they changes are not lost.

**Comment by tboerger** [comment]
Please look at the available env variables, it is already possible to change the upload site: https://github.com/owncloud-docker/base#available-environment-variables
