### ISSUE TITLE
where can i get this owncloud.tar.bz2 file?

### ISSUE THREAD

**Issue by 63949** [owncloud-docker/server#325]
https://github.com/owncloud-docker/server/blob/77644c7335356365e51ee90628e4e30fcdf7e020/v20.04/Dockerfile.amd64#L18

ADD owncloud.tar.bz2 /var/www/

where can i get this tar.bz2 file?
Could you pls inform?thx.

**Comment by xoxys** [comment]
Closed as answered. Feel free to add further questions.
