### ISSUE TITLE
Build performance bottleneck on /var/www/owncloud ownership setting 

### ISSUE THREAD

**Issue by SamuAlfageme** [owncloud-docker/server#33]
The other day I was building locally the image and noticed one layer took quite a while to be built:

https://github.com/owncloud-docker/server/blob/c8065bce5d7f1c122f7b8c17a22ec22feec0da84/Dockerfile#L21 

It got to the point I started thinking something was up with the tarball contents. After a few tests I think it's a performance issue with the rightmost side of the pipe: `xargs -r -0 chown www-data:www-data` - It takes unreasonably long to run that command. 

@tboerger have you noticed something similar in the docker-build system? Since `owncloud-docker/ubuntu` has bash > 4.0 maybe [_globstar_](https://www.gnu.org/software/bash/manual/html_node/The-Shopt-Builtin.html) can be used together with `chown -R` to improve readability/performance. 

Feel free to close if considered irrelevant.

**Comment by tboerger** [comment]
I have done a lot of benchmarking and the current script is the fastest option.

**Comment by tboerger** [comment]
If you can come up with a faster option please provide a PR, otherwise I'm closing this now.
