### ISSUE TITLE
Does Quick Evaluation version support https accessible

### ISSUE THREAD

**Issue by jack338c** [owncloud-docker/server#338]
@tboerger
I did exact like following :Just keep the owncloud container on port 8080 and let the reverse proxy handle port 443.
[https://github.com/owncloud-docker/server/issues/176](https://github.com/owncloud-docker/server/issues/176)
but always got failed
![Screen Shot 2022-09-26 at 2 53 00 PM](https://user-images.githubusercontent.com/10782586/192232444-a177c946-e93a-4fb1-b7e8-305b0704e780.png)
![Screen Shot 2022-09-26 at 2 53 20 PM](https://user-images.githubusercontent.com/10782586/192232587-6d832982-160a-4e39-ab2f-dbcd6480b8c2.png)
![Screen Shot 2022-09-26 at 2 54 05 PM](https://user-images.githubusercontent.com/10782586/192232635-b6501c5c-a010-4a34-8411-54ebfeb2185e.png)

Does Quick Evaluation version support https accessible?
[https://doc.owncloud.com/server/10.11/admin_manual/installation/docker/](https://doc.owncloud.com/server/10.11/admin_manual/installation/docker/)

I'm a new on owncloud,and want use it for my fmaily.now everying is fine except no https from outside network
I have installed Evaluation version of owncloud ony my openmediavault
and ssl file is prepared for my domain hom.xxx.xx,and it's been tested.they are ok
also have done portforwad on my router
I don't konw what's the reason or I did wrong configuration on Nginx Proxy Manager?
Please help me,I didn't find any tutorial of https accessible for the newest versoin of owncloud
![Screen Shot 2022-09-26 at 4 32 11 PM](https://user-images.githubusercontent.com/10782586/192232536-1fcef204-4daf-40b1-9fd2-c061e240c3f8.png)
![Screen Shot 2022-09-26 at 2 55 44 PM](https://user-images.githubusercontent.com/10782586/192232663-e8267bbc-568f-41d4-92cf-7f58b3dd853d.png)

**Comment by jack338c** [comment]
Sorry for that
and thanks for your explaining and correcting me.I just tested it.here are the result
 
![Screen Shot 2022-09-26 at 5 45 30 PM](https://user-images.githubusercontent.com/10782586/192246230-14d0ddd0-52e6-4246-b171-4ff1
![Screen Shot 2022-09-26 at 5 46 05 PM](https://user-images.githubusercontent.com/10782586/192246279-875f4e2e-3fa1-414d-83e7-7fcdd5de3755.png)
cf0b37dc.png)

![Screen Shot 2022-09-26 at 5 42 41 PM](https://user-images.githubusercontent.com/10782586/192246301-ffb3bc09-1f3b-4b96-bd4d-474b1b366b0d.png)
![Screen Shot 2022-09-26 at 5 40 46 PM](https://user-images.githubusercontent.com/10782586/192246318-d0b4fd80-880d-4802-b617-76446db1cf16.png)

**Comment by xoxys** [comment]
Looks like NAT is not properly configured in your home router, but that's a bit out of scope where I can help, as this is completely unrelated to ownCloud. You might want to search on the internet for this error message.

**Comment by jack338c** [comment]
my openwrt router has ddns function,like ddns-go, hom.xxx.xx ip is my router wan ip

I have tried with no https,it works
For example:  open http://hom.xxx.xx:8083 ,it will be forwarded to http://10.20.30.182:8080.if I set forward to 10.20.30.182:8080 on my openwrt router

**Comment by jack338c** [comment]
Now I switch to a supported installation with MariaDB and try use nginx to  active https by reverse proxy
but still get failed?

I tried lots of searching on internet.but no manual for this
I'm confused and a little upset with this now,Someone please help me.

![Screen Shot 2022-09-28 at 1 31 06 PM](https://user-images.githubusercontent.com/10782586/192695459-ed24e8d6-732c-4484-add2-1ea5671ced08.png)
![Screen Shot 2022-09-28 at 1 18 46 PM](https://user-images.githubusercontent.com/10782586/192695468-1f870952-b031-4ae1-aed4-2b47562d618b.png)
![Screen Shot 2022-09-28 at 12 55 13 PM](https://user-images.githubusercontent.com/10782586/192695470-ce09fbd4-f619-4474-be66-f19ed5f7eb94.png)
![Screen Shot 2022-09-28 at 12 23 08 PM](https://user-images.githubusercontent.com/10782586/192695474-1ca7d271-585e-4e14-8321-e8426ce2108f.png)

**Comment by tboerger** [comment]
As already stated above, you can potentially find help at https://central.owncloud.org/, this issue tracker is used for bug tracking and not for supporting to get the configuration/deployment right.

Beside that it's a little bit rude to directly highlight concrete people, especially when they aren't working for the company/project anymore.

**Comment by jack338c** [comment]
I got it.
Thank you and sorry for highlight you

**Comment by xoxys** [comment]
Closed in favor of https://central.owncloud.org/t/https-setup-for-external-access-omv/39423
