### ISSUE TITLE
ownCloud's configurations are being overwritten

### ISSUE THREAD

**Issue by happicamper** [owncloud-docker/server#34]
Hello, I just want to report that on my directory config which is a mounting point for my container is being overwritten such as database.config.php.
Whenever I rebuilt the container the configurations goes back to default resulting to fall back to sqlite(default database).
Does this behavior okay or can we have solution for this?
Thanks in advance.

**Comment by tboerger** [comment]
This is the expected behavior, you can change the configuration values with these available environment variables: https://github.com/owncloud-docker/base#available-environment-variables

**Comment by happicamper** [comment]
@tboerger I think your answer will lighten my mind about the configuration. Thank you very much. I will try this out.
