### ISSUE TITLE
Trusted domain does not work correctly

### ISSUE THREAD

**Issue by Bence98007** [owncloud-docker/server#344]
Hello,

I did try to find a solution on the forum, but everybody mentioned the trusted domain setting in the config.php.

My problem is that when I try to access my owncloud server from a client on the same network / or outside my network, it shows the error message:

> "You are accessing the server from an untrusted domain.
> Please contact your administrator. If you are an administrator of this instance, configure the "trusted_domains" setting in config/config.php. An example configuration is provided in config/config.sample.php or at the [documentation](https://doc.owncloud.com/server/10.11/go.php?to=admin-untrusted-domain)."

What I've tried/checked so far:

- My server is not behind a NAT (other docker containers can be reached outside from the LAN)
- I did try to add my URL to environment variable:
      `OWNCLOUD_DOMAIN=getlucky.ddns.net`
- I did edit the trusted domains setting in the config.php, now it looks like this:
` 'trusted_domains' =>
  array (
    0 => 'localhost',
    1 => 'localhost:8080',
    2 => 'getlucky.ddns.net',
    3 => 'getlucky.ddns.net:80',
    4 => 'getlucky.ddns.net:8080',
    5 => 'raspberrypi400',
    6 => 'raspberrypi400:80',
    7 => 'raspberrypi400:8080',
    8 => 'raspberrypi400.local',
    9 => 'raspberrypi400.local:80',
    10 => 'raspberrypi400.local:8080',
  ),
`
`'cors.allowed-domains' =>
  array (
    0 => 'localhost',
    1 => 'getlucky.ddns.net',
  ),
`
`  'overwrite.cli.url' => 'http://getlucky.ddns.net/',
`
I have this same docker-compose file on my other server in a different network, and it works, I didnt even have to edit anything related "trusted domains"...

I'm totally out of idea why this is not working.
Just wanted to ask this, maybe someone already found a solution, for me it took 5 hours until now.
Maybe there is a solution before Im gonna nuke my raspi and start again with Nextcloud.

Thanks :)

**Comment by phil-davis** [comment]
You need to define `OWNCLOUD_TRUSTED_DOMAINS` 

Example that I did for drone CI recently:

https://github.com/owncloud/core/pull/40438/files#diff-6a968d4b7901c8526c8d9a86d1f434737dbfe2b00da21a7d3041ed4e3d58d62eR2840

**Comment by xoxys** [comment]
Please use the forum for setup questions. We have a pinned topic that also links another topic where this question was answered already  https://central.owncloud.org/t/important-changes-to-owncloud-server-container-deployments/39642

**Comment by ho4ho** [comment]
owncloud-docker/base#238
