### ISSUE TITLE
Owncloud doesn't start

### ISSUE THREAD

**Issue by vashchenkov** [owncloud-docker/server#35]
I try to use this docker-compose.yml file. But owncloud can't be successfully configured. While updating old DB or creating new DB error 1036 has appear

`General error: 1036 Table '/tmp/#sql_b6_0.MAI' is read only`

After that I have set another image for db service
`
  db:
    image: mariadb:10.3.2
` 
And owncloud has been successfully started.

**Comment by tboerger** [comment]
Please start with a clean environment one more time, I have replaced the host volumes with named docker volumes.

**Comment by admlko** [comment]
I can confirm this still exists with clean installation. I am following ownCloud documentation to set it up with Docker, and it doesn't go into login screen as stated [here](https://doc.owncloud.org/server/latest/admin_manual/installation/docker/#logging-in) but it goes to first installation wizard instead (asking admin, data storage and db information).
If I fill them out, I get the same error as OP.

**Comment by tboerger** [comment]
Than you should provide more information or just replace the `webhippie/mariadb` with `mariadb`.

**Comment by admlko** [comment]
You are correct that replacing webhippie/mariadb with official mariadb fixed the issue.
Though it would be nice to provide useful information to fix the issue.

The OS is a clean minimal installation of CentOS 7 with Docker installed from their repo and followed ownCloud official docker documentation. SELinux is of course enabled, and turning it off is not a solution :)

You have to excuse my inability to provide more useful information by myself as this is my first Docker experiment.

**Comment by andystoeggle** [comment]
I face the same issue. The error getting thrown is:
`Error while trying to create admin user: An exception occurred while executing 'SELECT COLUMN_NAME AS Field, COLUMN_TYPE AS Type, IS_NULLABLE AS  'Null', COLUMN_KEY AS 'Key', COLUMN_DEFAULT AS 'Default', EXTRA AS Extra, COLUMN_COMMENT AS Comment, CHARACTER_SET_NAME AS CharacterSet, COLLATION_NAME AS Collation FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = 'owncloud' AND TABLE_NAME = 'oc_appconfig'': SQLSTATE[HY000]: General error: 1036 Table '/tmp/#sql_12c_0.MAI' is read only`
I have to use docker-compose v2 so I removed the `healtcheck`-Sections in each service, but I don't think this is responsible for the error. Additionally, my mariadb-Container runs on another host as the owncloud-Container but the connection seems to work properly

**Comment by tboerger** [comment]
@admlko looks like mariadb got some fix for apparmor hosts which webhippie/mariadb seems to be lacking because this issue only happens on redhat derivatives that got apparmor enabled, looks like I have to mention that within the readme until I get the webhippie/mariadb fixed.

@andystoeggle I think you are hitting a different issue, the docker-compose config is configured to enable utf8mb4, but to get this working it also requires changes to the used database. Please try to disable the utf8mb4 env variable and retry it with a clean state.

**Comment by andystoeggle** [comment]
@tboerger Thank you very much for the hint. I tried a few things and found [this](https://stackoverflow.com/a/48178214/4190467) SO conversation - I think this bug causes the problem. I'll work around with the official mariadb image (which is basically working) and setup the database manually.

**Comment by dschmidt** [comment]
@tboerger Isn't this issue valid then if the composer file does not work on all hosts? (I'm implying it should be reopened)

For anyone else who runs into this and for the time being wants to replace `webhippie/mariadb` with `mariadb`: The env vars for `mariadb` are called `MYSQL_` and not `MARIADB_` as for `webhippie/mariadb`.

**Comment by tboerger** [comment]
> @tboerger Isn't this issue valid then if the composer file does not work on all hosts? (I'm implying it should be reopened)

If the issue really relates to the docker-compose file, yes... But this is not really related to the docker-compose file itself, it's related to some kind of security limitation of the host system.

**Comment by dschmidt** [comment]
Ah, apparently this is a duplicate of https://github.com/owncloud-docker/server/issues/46 which already has more detailed information about how to get it work. So yeah, we can keep this closed ;-)

**Comment by tboerger** [comment]
When I found a proper solution I will give an update.

**Comment by oldthreefeng** [comment]
> How to replace that webhippie/mariadb with mariadb?


Have you solved this problem?

**Comment by StefanWeiss2787** [comment]
> > How to replace that webhippie/mariadb with mariadb?
> 
> Have you solved this problem?

Yeah for me was fairly easy. Ditch the official owncloud docker install and just go straight for the image provided... no dokcer-compose no nothing just get the docker image (i think this: https://hub.docker.com/_/owncloud/) up and running

**Comment by tboerger** [comment]
> Yeah for me was fairly easy. Ditch the official owncloud docker install and just go straight for the image provided... no dokcer-compose no nothing just get the docker image (i think this: https://hub.docker.com/_/owncloud/) up and running

The "official" image is not maintained by ownCloud, it's maintained by Docker Inc, besides that this image is deprecated.

> Have you solved this problem?

Just replace `webhippie/mariadb` with `mariadb` and replace the env variables.

**Comment by mario462** [comment]
> @tboerger Isn't this issue valid then if the composer file does not work on all hosts? (I'm implying it should be reopened)
> 
> For anyone else who runs into this and for the time being wants to replace `webhippie/mariadb` with `mariadb`: The env vars for `mariadb` are called `MYSQL_` and not `MARIADB_` as for `webhippie/mariadb`.

Quick note here, don't take this literally 😅I just spent a good amount of time figuring out why I didn't have access to my database. Turns out _mysql_ env variable for user is `MYSQL_USER`, which is named <code>MARIADB_USER<b>NAME</b></code> for _mariadb_. Hope this helps someone 😁
