### ISSUE TITLE
table prefix bug?

### ISSUE THREAD

**Issue by skironDotNet** [owncloud-docker/server#357]
Here is the story to give you more background 
I have OC 10.5 "normal" installation, so Apache/PHP everything works
Decided to go docker, created custom docker-compose based on official, just wan to use non-combo DB external dockerized mysql and don't want to use docker volumes just bare old-fashion volumes. Exported DB data to new DB
Spent like 16h already to make everything work lol. Have set all the permissions  
![image](https://user-images.githubusercontent.com/2981715/208254160-aec6f8fd-e194-48a4-a175-329c81c0322c.png)

The container started just fine, I have 'temp' user as env startup admin since existing 'admin' was in the DB
and the DB migration went fine (using OC latest 10.11)

First login as existing  admin was fine but I see no files just a popup `Directory “/” not found`, ok looked in oc_storages, deleted dead entry.
Login again I see the file structure, but can't load anything

![image](https://user-images.githubusercontent.com/2981715/208254295-afcdbb76-b9ee-4cab-9436-b5c2bc3c6281.png)

So I'm thinking let's login as 'temp' user created by the container on first start, this is what I get

![image](https://user-images.githubusercontent.com/2981715/208254323-d06064e9-7267-4bf7-80ef-1dcec6bfc9e9.png)

So I'm searching online and found advice like run `./occ files:scan --all` and the bug begins, complaining `db_name.appconfig` table doesn't exist 

![image](https://user-images.githubusercontent.com/2981715/208254363-faab270b-14c6-4c82-82aa-40fcc49b8028.png)

Well it doesn't because everything starts as `oc_`

![image](https://user-images.githubusercontent.com/2981715/208254423-a3a0fd93-d15d-4971-90a8-62d667378714.png)

and config confirms `oc_` prefix  

![image](https://user-images.githubusercontent.com/2981715/208254449-12f8180a-03e3-4301-9ead-d5db09746c65.png)

Why occ fired in the container is not using `oc_` prefix?

Thanks for reading

**Comment by skironDotNet** [comment]
My bad, apparently I wasn't using proper way to use occ (the container thinking)
So did it this way https://doc.owncloud.com/server/next/admin_manual/installation/docker/#running-occ-commands
got more friendly error :)

![image](https://user-images.githubusercontent.com/2981715/208254840-e93f32de-1006-4c25-96c9-273128665314.png)

**Comment by skironDotNet** [comment]
So based on this https://github.com/owncloud/core/issues/25755#issuecomment-343896700 makes sense the 'home' column has old values from prev server

![image](https://user-images.githubusercontent.com/2981715/208255077-8ce7c1d1-db82-4318-93e7-6cf1c314b528.png)

I guess the bug is in DB migration script, I think it should update that value based on `datadirectory` config

**Comment by xoxys** [comment]
That is still not a container issue. Please use the forum as suggested on your last issue already or continue in the owncloud/core issue.
