### ISSUE TITLE
Several Windows issues

### ISSUE THREAD

**Issue by PR3M1UM** [owncloud-docker/server#36]
Hi. I'm running Docker for Windows and I am following these instructions: https://doc.owncloud.org/server/10.0/admin_manual/installation/docker/
I set all the .env variables:
```
VERSION=10.0.4
DOMAIN=localhost
ADMIN_USERNAME=admin
ADMIN_PASSWORD=password
HTTP_PORT=83
HTTPS_PORT=4444
```
And ran `docker-compose up`. All containers have been initialized and are running according to `docker-compose ps`. Now the config.php file looks like this:
```<?php
$CONFIG = array(
  "data_directory" => "/mnt/data/files",
  "apps_paths" => array(
    0 => array(
      "path" => OC::$SERVERROOT . "/apps",
      "url" => "/apps",
      "writable" => false
    ),
    1 => array(
      "path" => OC::$SERVERROOT . "/custom",
      "url" => "/custom",
      "writable" => true
    )
  )
);
```
When navigating to https://localhost:4444, I see a config window(?).

Issue 1:
I expect a regular login window, but here I must create an admin account and specify the MySQL connection and the location of the data folder. I set the data folder to the location ` "/mnt/data/files"` and the MySQL configs to the ones given in the docker-compose file.

Issue 2:
When the setup completed, I received the error, saying that the data directory is visible to other users and that I should change the folder permissions to 0770. I can't proceed. The config.php file now looks like this:
```
<?php
$CONFIG = array (
  'data_directory' => '/mnt/data/files',
  'apps_paths' => 
  array (
    0 => 
    array (
      'path' => '/var/www/owncloud/apps',
      'url' => '/apps',
      'writable' => false,
    ),
    1 => 
    array (
      'path' => '/var/www/owncloud/custom',
      'url' => '/custom',
      'writable' => true,
    ),
  ),
  'dbtype' => 'mysql',
  'dbhost' => 'db',
  'dbname' => 'owncloud',
  'dbuser' => 'owncloud',
  'dbpassword' => 'owncloud',
  'dbtableprefix' => 'oc_',
  'trusted_domains' => 
  array (
    0 => 'localhost:4444',
  ),
  'mysql.utf8mb4' => true,
  'instanceid' => 'oc52d4enaqc9',
  'passwordsalt' => '<salt here>',
  'secret' => '<secret here>',
  'datadirectory' => '/mnt/data/files',
  'overwrite.cli.url' => 'https://localhost:4444',
  'version' => '10.0.4.4',
  'logtimezone' => 'UTC',
  'installed' => true,
);
```

Issue 3:
When I check the config.php file, I see duplicate configs: `"data_directory"` and `"datadirectory"`.

Issue 4:
Redis seems to be unused. The volume folder on my host is empty. There is no redis configuration present in config.php.

Issue 5:
Because the user files are not shared with my host machine, running `docker-compose down` will destroy all user files. When bringing up the docker containers I receive the error that the data directory is invalid - it must contain .ocdata.

Can anyone reproduce this? What am I doing wrong? I'm not a docker expert.

**Comment by tboerger** [comment]
1) This indicates that the setup have not been finished successfully. I can not provide any further help without any log output.

2) I have never tried it on Windows, possibly you should use named volumes at all on Windows to avoid this since it doesn't support file permissions like a Linux system.

3) Not a critical issue, but something we can check, please raise a dedicated issue for that.

4) Redis gets configured if the setup/start works without issues, please look at 1).

5) This problem doesn't exist on Linux machines, please look at 2).

**Comment by PR3M1UM** [comment]
Hello @tboerger. Thank you for your super fast response!

Here are the logs when I perform a fresh start: https://pastebin.com/ZVk47L4N
It appears that there is something going on with config.php permissions. You are right, it's a volume problem. This is what I did to solve the issue:

**docker-compose.yml:**
```
services:
  owncloud:
    ...
    volumes:
      - ./certs:/mnt/data/certs
      - oc-data: /mnt/data

...

volumes:
  oc-data:
```

I only mounted the _certs_ folder so I can still use my own certificates. Now the start log looks like this: https://pastebin.com/dLYR1CQK. It works perfect now. I can also destroy all containers without losing data. However, it would be nice to access the config file through a volume aswell. Is that possible by running a few extra chmod commands maybe? I also see that the redis volume folder is still empty. Is that okay?

**Comment by tboerger** [comment]
Maybe I have to rewrite the example config generally to named volumes. You can always use docker-compose exec owncloud occ or similar commands to manipulate the config within the docker container context. Beside that you can also use docker cp to copy certificates into the container or volume. So there is no real need to provide host volumes.

The redis volume is only used for redis dumps, it's OK if it's empty.

**Comment by PR3M1UM** [comment]
Thanks!
