### ISSUE TITLE
"trusted_doamins" cannot work anymore for docker container.

### ISSUE THREAD

**Issue by PatrickHsu36** [owncloud-docker/server#379]
ownCloud 10.10 and above is forced request to use OWNCLOUD_TRUSTED_DOMAINS for docker container ONLY. But that is really not a good design for using the docker container. While users want to add another trusted domain, he need to stop container, edit the env, start it again. While update the container, the settings may need to change again. Since this kind of design, some people met the problem, and they always don't understand, why the trusted_domains in config.php cannot work anymore. But config.php is designed for users to edit or add extra and specific configuration by himself, but ownCloud break this kind of normal behavior for docker container users, it's not user friendly.
Anyway, this is the opinion by users, I think this is not a good design for use.

I provide a package for NAS users to install and use ownCloud on the NAS, and many users complain to me that they cannot change trusted_domains via config.php anymore, and they may not know well with docker container, and how to change the env of container. (The change MUST be done once the container is updated.)

**Comment by xoxys** [comment]
The `config.php` file was never intended to work while using the container, and it has never worked reliably for all the other settings that are available as environment variables. ownCloud loads the configuration files from the config folder in alphabetical order (last wins). By default for the container this is:

```
root@40b2301219b0:/var/www/owncloud# ls -l /mnt/data/config/
total 28
-rw-r-----. 1 www-data www-data  1214 Mar 14 07:58 config.php
-rw-r--r--. 1 root     root      1038 Mar 14 07:58 objectstore.config.php
-rw-r--r--. 1 www-data root     18749 Mar 14 07:58 overwrite.config.php
```

If you want to set it via file, you can create another one, e.g. `zz-user.config.php` that will be loaded last and overwrite the default files. Why `OWNCLOUD_TRUSTED_DOMAINS` was introduced were discussed in details already and there are no plans to change this behavior, sorry.

**Comment by PatrickHsu36** [comment]
> If you want to set it via file, you can create another one, e.g. `zz-user.config.php` that will be loaded last and overwrite the default files.

Thanks for providing this solution, I had tried, and it works.

**Comment by PatrickHsu36** [comment]
> If you want to set it via file, you can create another one, e.g. `zz-user.config.php` that will be loaded last and overwrite the default files.

Thanks for providing this solution, I had tried, and it works.
