### ISSUE TITLE
owncloud/server:10.0.4,sql error :1036

### ISSUE THREAD

**Issue by MRwangyd** [owncloud-docker/server#38]
![qq 20180111160055](https://user-images.githubusercontent.com/27405334/34814414-81394546-f6e8-11e7-93a8-317bc6f2a358.png)
The installation  owncloud/server:10.0.4,in the web configuration.
A database error occurred.
![qq 20180111155744](https://user-images.githubusercontent.com/27405334/34814398-68cfc746-f6e8-11e7-8290-994663225458.png)

Please help to solve the problem.

**Comment by MRwangyd** [comment]
Just replace the mirror,Configuration does not need to change.

**Comment by MRwangyd** [comment]
Is that so?

**Comment by MRwangyd** [comment]
After the official image is replaced, it can be used for production, but it must be installed once by webhippie/mariadb, and the image can be replaced after the data catalog is generated.
Can't be started directly with the official mirror container.

**Comment by tboerger** [comment]
You have to start a fresh state with the official image, that should solve the issue. I have to further debug why the webhippie image stopped working.

**Comment by MRwangyd** [comment]
Okay thank you
