### ISSUE TITLE
config.php file cannot be read as default. 

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud-docker/server#4]
Hi, I've just tried this image/images and I am getting a permissions error on config.php.

```
PHP Warning:  fopen(/var/www/owncloud/config/config.php): failed to open stream: Permission denied in /var/www/owncloud/lib/private/config.php on line 187
```

Config dir is mounted as a volume. 

Perhaps there is a step needed before running it?

**Comment by felixboehm** [comment]
should be fixed, please retry
