### ISSUE TITLE
Watermarked LDAP buttons

### ISSUE THREAD

**Issue by happicamper** [owncloud-docker/server#40]
Hello, I'd like to ask if this is related to this repository. If not please redirect me wherever is appropriate.
My issue is I cannot click buttons in LDAP such as Detect port, Test Base DN.
I'm seeing logs such as : 
```
"Configuration Error (prefix s01): login filter does not contain %uid place holder."}
"Configuration Error (prefix s01): No LDAP Login Filter given!"}
"Configuration Error (prefix s01): Not a single Base DN given."}
```
Even though I've supplied all of those. 
Thank you in advance.

**Comment by tboerger** [comment]
This is not related to this repository, please report it upstream at https://github.com/owncloud/user_ldap
