### ISSUE TITLE
err log "ownCloud is not installed"

### ISSUE THREAD

**Issue by yellowsoar** [owncloud-docker/server#41]
I run owncloud container behind an nginx reverse proxy on a centos server.
Using iptables instead of firewalld since it's a mess between firewalld and docker...(TL;DR)
Setting whitelist policy on iptables.(DROP all in INPUT and FORWARD chain)
And ACCEPT all from IP range 172.16.0.0 - 172.31.255.255 in DOCKER-USER chain.
(Since all my other container works just fine, I think the firewall is not the problem.)

After `docker-compose up`, I can access index.php from my pc via domain that I've setted in `.env`.
(So, I guess that means nginx reverse proxy is fine here in my situation?)
And owncloud ask me to set an admin account for first time use.
But I did set admin account in `.env` file. So, it seems something goes wrong.

I followed the steps to set admin accout.
But, it only works when database is set to SQLite.
Otherwise, MySQL/MariaDB and PostgreSQL shows error log on web page:
`Error while trying to create admin user: Failed to connect to the database: An exception occured in driver: SQLSTATE[HY000] [2002] No such file or directory`

I try to login after the admin accout was setted by choosing SQLite.
But got internal error 500 on web page. And the log in docker-compose:
` 123.123.123.123 - - [26/Jan/2018:09:58:24 +0000] "POST /index.php/login?redirect_url=%252Findex.php%252Fapps%252Ffiles%252F HTTP/1.0" 500 7095 "-" "Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:58.0) Gecko/20100101 Firefox/58.0"`
At the same time, health check is ok:
`127.0.0.1 - - [26/Jan/2018:10:01:27 +0000] "GET /status.php HTTP/1.1" 200 1122 "-" "curl/7.47.0"`

I checked the log while container is creating, and got repeated error logs:
` ownCloud is not installed - only a limited number of commands are available`
The full log is in the attachment [log.txt](https://github.com/owncloud-docker/server/files/1667437/log.txt)

My `.env` file:
```
VERSION=10.0.x
DOMAIN=www.domain.com
ADMIN_USERNAME=admin
ADMIN_PASSWORD=admin
HTTP_PORT=10080
HTTPS_PORT=10443
```

I've tried version 10.0 to 10.0.4, but all failed.
The nginx reverser proxy is set to redirect http and https packages from 80 and 443 to 10080.

My env:
docker Version: 17.12.0-ce
docker-compose version 1.18.0, build 8dd22a9
Kernel Version: 3.10.0-693.11.6.el7.x86_64
Operating System: CentOS Linux 7

Anyone can help?

**Comment by tboerger** [comment]
Please try to use only named volumes, or append `:z` to the used host volumes, that could cause issues on CentOS/RHEL/Fedora.

**Comment by yellowsoar** [comment]
@tboerger Thanks! But...it's the same. I still got "ownCloud is not installed" error log.

**Comment by tboerger** [comment]
Please give the official mysql container a try and start with a fresh workspace (drop the data directory). There had been reports that webhippie/mariadb is broken in some scenarios.

**Comment by yellowsoar** [comment]
@tboerger 
Well...you are right.
Official [mariadb](https://hub.docker.com/_/mariadb/) works. (cheers)

I checked the logs again and found something....
Owncloud is stuck while installing server database to webhippie/mariadb.
So, the reports about webhippie/mariadb is now confirmed.

Here's my compose file:
```
  db:
    image: mariadb:latest
    restart: always
    environment:
      - MYSQL_DATABASE=owncloud
      - MYSQL_ROOT_PASSWORD=owncloud
      - MYSQL_USER=owncloud
      - MYSQL_PASSWORD=owncloud
    volumes:
      - ./volumes/mysql:/var/lib/mysql:z
```

BTW, all mariadb 10.0-10.3 works fine.
