### ISSUE TITLE
Postgres Support while running in Docker?

### ISSUE THREAD

**Issue by JKomoroski** [owncloud-docker/server#42]
Hello,

It looks like enabling postgres support requires changes to a php file ([Documentation Link](https://doc.owncloud.org/server/latest/admin_manual/configuration/database/linux_database_configuration.html?highlight=postgres#db-postgresql-label)), and is therefore not currently supported by this docker image. If that is the case, are there any plans to provide an official postgres compatible container?

Thanks!

**Comment by tomneedham** [comment]
you must set the `dbtype` to `pgsql` in config.php

**Comment by patrickjahns** [comment]
@JKomoroski 

It should already be possible - see: 
https://github.com/owncloud-docker/base/blob/master/rootfs/etc/owncloud.d/15-database.sh#L19

**Comment by JKomoroski** [comment]
I had misspelled the flag when testing. Thank you!
