### ISSUE TITLE
[QA] integrity checker fails in 10.13.1

### ISSUE THREAD

**Issue by jnweiger** [owncloud-docker/server#425]
Seen with 10.13.1 (regression, was not seen with 10.13.1-rc.1)

* `docker run --rm -ti -p 6660:8080 owncloud/server:10.13.1`
* Work a while with the system so that system cron kicks in (or manually run `occ integrity:check-core`)
* Visit admin general settings, an integrity checker alert is shown. BAD
![grafik](https://github.com/owncloud-docker/server/assets/1108546/dcbaf789-97c6-48ab-8390-6bc48942f699)

----
* Click on details:
```
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- core
	- FILE_MISSING
		- lib/composer/pimple/pimple/src/Pimple/Tests/Fixtures/Invokable.php
		- lib/composer/pimple/pimple/src/Pimple/Tests/Fixtures/NonInvokable.php
		- lib/composer/pimple/pimple/src/Pimple/Tests/Fixtures/PimpleServiceProvider.php
		- lib/composer/pimple/pimple/src/Pimple/Tests/Fixtures/Service.php
		- lib/composer/pimple/pimple/src/Pimple/Tests/PimpleServiceProviderInterfaceTest.php
		- lib/composer/pimple/pimple/src/Pimple/Tests/PimpleTest.php
		- lib/composer/pimple/pimple/src/Pimple/Tests/Psr11/ContainerTest.php
		- lib/composer/pimple/pimple/src/Pimple/Tests/Psr11/ServiceLocatorTest.php
		- lib/composer/pimple/pimple/src/Pimple/Tests/ServiceIteratorTest.php
- openidconnect
	- FILE_MISSING
		- vendor/jumbojett/openid-connect-php/tests/OpenIDConnectClientTest.php
		- vendor/jumbojett/openid-connect-php/tests/TokenVerificationTest.php
		- vendor/jumbojett/openid-connect-php/tests/data/jwks-ps256.json
- oauth2
	- FILE_MISSING
		- vendor/rowbot/url/tests/ToASCIIWindowTest.php
		- vendor/rowbot/url/tests/URLConstructorTest.php
		- vendor/rowbot/url/tests/URLEncodedParserTest.php
		- vendor/rowbot/url/tests/URLOriginTest.php
		- vendor/rowbot/url/tests/URLSearchParamsAppendTest.php
		- vendor/rowbot/url/tests/URLSearchParamsConstructorTest.php
		- vendor/rowbot/url/tests/URLSearchParamsDeleteTest.php
		- vendor/rowbot/url/tests/URLSearchParamsForeachTest.php
		- vendor/rowbot/url/tests/URLSearchParamsGetAllTest.php
		- vendor/rowbot/url/tests/URLSearchParamsGetTest.php
		- vendor/rowbot/url/tests/URLSearchParamsHasTest.php
		- vendor/rowbot/url/tests/URLSearchParamsSetTest.php
		- vendor/rowbot/url/tests/URLSearchParamsSortTest.php
		- vendor/rowbot/url/tests/URLSearchParamsStringifierTest.php
		- vendor/rowbot/url/tests/URLSettersTest.php
		- vendor/rowbot/url/tests/URLToJSONTest.php
		- vendor/rowbot/url/tests/failureTest.php
		- vendor/rowbot/url/tests/setters_tests.json
		- vendor/rowbot/url/tests/toascii.json
		- vendor/rowbot/url/tests/urltestdata.json	
```

Core and apps are signed by signature.json to assert the exact state that was configured during release is actually running.
Please revert #424 

Sorry to report a bug introduced between RC 1 and final. Please use beta-phase for such changes, then we have time to discuss proper solutions.

**Comment by xoxys** [comment]
I would really appreciate more in time reviews...

**Comment by jnweiger** [comment]
Me too. We need bug reports against the 3rd-party components bundle test suites in their production deliverables, or script test suite removal during integration and before signing. @DeepDiver1975 did that already for graphapi, but that needs to be carefully 
reviewed on a case by case basis - a directory name does not really tell us if code is used in production or not.

owncloud-docker/server-10.12.2 is also fails integrity checks; owncloud-docker/server-10.13.0 passes integrity checks.

**Comment by xoxys** [comment]
> owncloud-docker/server-10.13.0 passes integrity checks.

Because we don't rebuild patch releases...
