### ISSUE TITLE
Problem with ca-bundle in docker container

### ISSUE THREAD

**Issue by kovalroma** [owncloud-docker/server#43]
Hello!
I need to edit Apache conf (SSLCertificateChainFile) in owncloud container to add ca-bundle file (my certificate depends on intermediate certs) 

For now it's impossible because /etc/apache2/enabled/ doesn't share as volume. 
I've tried add intermediate cert to /data/config/ca-bundle.crt and this doesn't help.
Only edition in 000-default.conf resolve my SSL warning. But after I restart docker-compose my edition disappear.

**Comment by tboerger** [comment]
You can simply mount the host file /etc/ssl/certs/ca-certificates.crt sich includes your ca into the same path within the container and it should work. We are doing it exactly like that internally.
