### ISSUE TITLE
Start container in maintenance mode

### ISSUE THREAD

**Issue by nilo72** [owncloud-docker/server#47]
Hi there, 

I want to start a new container in maintenance mode. Is it possible to do so with an envinronment-variable?

**Comment by tboerger** [comment]
This is nothing we have done so far, but maybe we can simply add an environment variable for that to enforce the maintenance mode.

**Comment by nilo72** [comment]
If it's simple can I help myself to add the OWNCLOUD_MAINTENANCEMODE environment variable?
Am i rigth that the variables are set with the occ-command which is called in /usr/local/bin/owncloud-installer? How do the scripts are deployed into the docker-image?

**Comment by tboerger** [comment]
The entire scripting is defined with the https://github.com/owncloud-docker/base repository. You could define the default for the variable within https://github.com/owncloud-docker/base/blob/master/rootfs/etc/entrypoint.d/10-base.sh and you can use this variable within one of the scripts you can find at https://github.com/owncloud-docker/base/tree/master/rootfs/etc/owncloud.d. The scripts are executed in alphabetical order.

**Comment by tboerger** [comment]
Solved via https://github.com/owncloud-docker/base/pull/20
