### ISSUE TITLE
GET /status.php HTTP/1.1 Message repeated

### ISSUE THREAD

**Issue by itsCasper** [owncloud-docker/server#54]
Thank you for the advice to run a pull for docker. #53 
That has provided a better starting process. But when run without the -d I see the message regarding GET /status.php repeated and owncloud does not give an error or start completely.

Is there something I should look to change in the macOS, or in the config files for owncloud?

Thank you

<img width="778" alt="screenshot 2018-05-02 12 04 32" src="https://user-images.githubusercontent.com/38891795/39535248-71843460-4e01-11e8-9fff-b9609e607f3d.png">

**Comment by itsCasper** [comment]
I am adding here the lines in the startup that appear before the repeated GET command. Hope this helps possibly to explain where the issue may be.

<img width="970" alt="screenshot 2018-05-02 12 08 55" src="https://user-images.githubusercontent.com/38891795/39535361-b66c3564-4e01-11e8-84b7-206e35f1edfe.png">

**Comment by tboerger** [comment]
The repeated status.php is not an issue at all, this is just the log line related to the docker healthcheck. Looks like the instance is running fine.

**Comment by itsCasper** [comment]
Thank you for clarifying that.  You are correct the server is running and they all show as healthy.  However I am not able to access the localhost using either http or https.  I can err empty repsonse or unable to establish secure connection to the server from both Safari and Chrome.
I did attempt another fix in troubleshooting.  The advice was to change the db to library/mariadb:latest/ which pulled down the latest version of the MariaDB.  That was causing an unhealty message in the ps status.  I since changed it back to the webhippie statement, get the healthy message, but am unable to access the webpage for the server once running.
The server is listening on ports 9090 and 9443 which had to be specified as it is running macOS server even with websites off those ports are commandeered.
Is it possibe the db issues could be causing the site to be unavailble? I am not even sure where to look for the logs to identify where the failure might be.
Or is it possible to remove the db and have the owncloud pull and run from scratch again?

**Comment by tboerger** [comment]
You can always call docker-compose down -v to start from the scratch.

You have only changed to ports within the .env file?

**Comment by itsCasper** [comment]
I was following the documentation each time a change was made. Stop, down then pico and edited both the yml and env file to match on ports. Then ran up -d and all processes start and show healthy.
Further checks and curl shows no response from the localhost:port. Either for http and https.
Net stat shows that the ports are being listened on.
This is all being tested on the host server. If the -v command would start all from scratch that could prove easier.
Thank you for the help. If you would like more detail please let me know what command I could run.

Casper Jones | Digital Lead Technologist
416.826.7659 | byuagency.com
________________________________

**Comment by tboerger** [comment]
You should only change the host binding port within the .env, you can't change the container port within the docker-compose.yml, that won't work.

If you still encounter issues please write to this issue.
