### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by danieldeusing** [owncloud-docker/server#55]
Since I have installed owncloud with the docker image I get server crashes. It never happens if owncloud is not running.

It is a vServer. Do you have any idea what causes this problem (I was not able to scroll up in the console, so I only have this screen)?

[https://imgur.com/a/k5iKnMj](https://imgur.com/a/k5iKnMj)

`docker-compose version 1.18.0, build 8dd22a9`

`Docker version 18.03.1-ce, build 9ee9f40`

```
PRETTY_NAME="Debian GNU/Linux buster/sid"
NAME="Debian GNU/Linux"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
17.5.3 debian8.0.build1705170317.16
```

**Comment by tboerger** [comment]
If it's a vserver maybe it's related to the resource usage? The stack trace doesn't look like it's directly related to owncloud, I guess it happens while the cron execution.

I can't see anything where I could help and this is the first report like that.

**Comment by danieldeusing** [comment]
Okay, thanks for your comment, it will help me to investigate further. If I know something I will let you know.

The only thing I can tell is that on this sever there are several docker images running and it really only happens with that particular docker instance

**Comment by tboerger** [comment]
Doesn't look like it's directly related to owncloud docker images, so closing this issue.
