### ISSUE TITLE
Error loading activities

### ISSUE THREAD

**Issue by sfmarques** [owncloud-docker/server#56]
I get this error when clicking in Activities or in the file. I have Docker ownCloud 10.0.7.2, upgrade to ownCloud 10.0.8.5 and have the same error:

![image](https://user-images.githubusercontent.com/5604227/39696703-670b71ae-51e6-11e8-8647-035efec49cbd.png)

**Comment by tboerger** [comment]
Do you have any logs? Generally it sounds like an upstream error without more information.

**Comment by sfmarques** [comment]
Sorry,

Doing docker logs i find this error whenever i click in front of the document name:

[07/May/2018:10:17:14 +0000] "PROPFIND /remote.php/dav/systemtags-relations/files/1421 HTTP/1.1" 207 1094 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:59.0) Gecko/20100101 Firefox/59.0"

**Comment by tboerger** [comment]
I can't reproduce this issue locally with the current 10.0.7 docker image, please report an issue to the owncloud upstream repository with full debugging information.

![bildschirmfoto 2018-05-07 um 13 46 36](https://user-images.githubusercontent.com/156964/39700342-1d235d60-51fd-11e8-98a1-63bdb53345ce.png)
