### ISSUE TITLE
Update owncloud.org documentation

### ISSUE THREAD

**Issue by jonathandean** [owncloud-docker/server#57]
I'm not sure where to file this so I'm trying here in hopes that if it's the wrong place someone can point me to the correct one. The documentation here no longer works: https://doc.owncloud.org/server/latest/admin_manual/installation/docker/#installation-on-a-local-machine

Errors are:

```
> docker-compose up -d
WARNING: The OWNCLOUD_VERSION variable is not set. Defaulting to a blank string.
WARNING: The OWNCLOUD_DOMAIN variable is not set. Defaulting to a blank string.
...
ERROR: no such image: owncloud/server:: invalid reference format
```

It appears that `VERSION` and `DOMAIN` need to be replaced with `OWNCLOUD_VERSION` and `OWNCLOUD_DOMAIN` in this step:

```
# Create the environment configuration file
cat << EOF > .env
VERSION=10.0.4
DOMAIN=localhost
ADMIN_USERNAME=admin
ADMIN_PASSWORD=admin
HTTP_PORT=80
HTTPS_PORT=443
EOF
```

which would then be:
```
# Create the environment configuration file
cat << EOF > .env
OWNCLOUD_VERSION=10.0.4
OWNCLOUD_DOMAIN=localhost
ADMIN_USERNAME=admin
ADMIN_PASSWORD=admin
HTTP_PORT=80
HTTPS_PORT=443
EOF
```

Might be even best to make sure that it points to the latest version instead of needing to go back and update those instructions periodically:

```
# Create the environment configuration file
cat << EOF > .env
OWNCLOUD_VERSION=latest
OWNCLOUD_DOMAIN=localhost
ADMIN_USERNAME=admin
ADMIN_PASSWORD=admin
HTTP_PORT=80
HTTPS_PORT=443
EOF
```

**Comment by tboerger** [comment]
Yes, the latest changes to this repository have not been updated within https://github.com/owncloud/documentation yet, I will create an issue over there. Let's see if somebody contributes these changes or if I have to jump in.

**Comment by tboerger** [comment]
But anyway thank you for the report/hint ;)

**Comment by tboerger** [comment]
Now I have directly created pull requests to update the documentation...
