### ISSUE TITLE
enabling contacts app from marketplace results in internal server error

### ISSUE THREAD

**Issue by Kawohl** [owncloud-docker/server#6]
I

Steps to reproduce

Have owncloud 9.1.5 installed with ldap
Disable user_ldap before updating to 10.0.4 RC4
3.Install contacts from marketplace.
Expected behaviour

App should work

Actual behaviour

{"reqId":"fYx4cw7YA2kvkEOmcfMW","level":3,"time":"2017-04-25T08:46:07+00:00","remoteAddr":"172.18.0.1","user":"admin","app":"index","method":"GET","url":"/index.php/apps/files/","message":"Exception: {"Exception":"RuntimeException","Message":"image not found: image:app.svg webroot: serverroot:/var/www/owncloud","Code":0,"Trace":"n#0 /mnt/data/apps/contacts/appinfo/app.php(35): OC\URLGenerator->imagePath('contacts', 'app.svg')n#1 /var/www/owncloud/lib/private/NavigationManager.php(95): OC_App::OCA\Contacts\AppInfo{closure}()n#2 /var/www/owncloud/lib/private/legacy/app.php(692): OC\NavigationManager->getAll()n#3 /var/www/owncloud/lib/private/TemplateLayout.php(76): OC_App::getNavigation()n#4 /var/www/owncloud/lib/private/legacy/template.php(230): OC\TemplateLayout->__construct('user', 'files')n#5 /var/www/owncloud/lib/public/AppFramework/Http/TemplateResponse.php(156): OC_Template->fetchPage()n#6 /var/www/owncloud/lib/private/AppFramework/Http/Dispatcher.php(112): OCP\AppFramework\Http\TemplateResponse->render()n#7 /var/www/owncloud/lib/private/AppFramework/App.php(98): OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\Files\Controller\ViewController), 'index')n#8 /var/www/owncloud/lib/private/AppFramework/Routing/RouteActionHandler.php(46): OC\AppFramework\App::main('ViewController', 'index', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)n#9 [internal function]: OC\AppFramework\Routing\RouteActionHandler->__invoke(Array)n#10 /var/www/owncloud/lib/private/Route/Router.php(299): call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array)n#11 /var/www/owncloud/lib/base.php(909): OC\Route\Router->match('/apps/files/')n#12 /var/www/owncloud/index.php(49): OC::handleRequest()n#13 {main}","File":"/var/www/owncloud/lib/private/URLGenerator.php","Line":164}"}

"Message":"image not found: image:app.svg seems to be the problem here.

I guess there is something wrong with permissions or the symlink in /mnt/data apps.

**Comment by Kawohl** [comment]
I suspect that the apps folders permissions or rewrite doesn't fuction properly if the  container is update by copying the new tar ball to /var/www

**Comment by tboerger** [comment]
You should not copy anything to /var/www manually. Just use the new version of the container and launch the updated version.
