### ISSUE TITLE
user_ldap download link is not existed

### ISSUE THREAD

**Issue by bum2free** [owncloud-docker/server#61]
wget https://github.com/owncloud/user_ldap/releases/download/0.10.0/user_ldap.tar.gz

**Comment by bum2free** [comment]
er, it just typ error, miss "v", so it should be
wget https://github.com/owncloud/user_ldap/releases/download/v0.10.0/user_ldap.tar.gz

**Comment by tboerger** [comment]
Right, this got to be fixed within the readme. The CI system is using a link including the `v`.

**Comment by tboerger** [comment]
Solved via https://github.com/owncloud-docker/server/commit/1f94a5e39c871f20e2924b64e0136208dbaed467
