### ISSUE TITLE
Consider using PHP as base image and providing FPM variants

### ISSUE THREAD

**Issue by J0WI** [owncloud-docker/server#62]
You might be aware of https://github.com/docker-library/owncloud.
Sadly this is going to be [deprecated](https://github.com/docker-library/docs/pull/1251) by the end of this year in favor of this one. This repo uses a fairly different approach to build the image. It's based on the [PHP base image](https://hub.docker.com/_/php/) and provides FPM variants, that can be easily combined with your favorite (dockerized) HTTP server.

It would be great if you could pick up this approach.
It's also possible to [take over the existing repository](https://github.com/docker-library/official-images#maintainership).

**Comment by tboerger** [comment]
So far it's not planned to use the official PHP images, beside that we have limited the container to the officially supported stack on purpose. So currently there are no plans to change this behavior, but thank you for your feedback.
