### ISSUE TITLE
Can't access with HTTP - for reverse proxy'ing

### ISSUE THREAD

**Issue by benjaminlyng** [owncloud-docker/server#73]
Hi.
I want to run my owncloud behind a reverse proxy to have more services on the same server. I've been looking at [https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion](url) which could also handle ssl. But as i understand it this takes http and then encrypts it. My attempts so far got me a 502 - bad gateway, which i guess is because owncloud is already ssl encrypted.
So my problem is: how can i get access with http without being redirected to https?

**Comment by tboerger** [comment]
Just access port 80 on the container and you can easily use Nginx or any reverse proxy for SSL termination.

**Comment by tboerger** [comment]
BTW, I would suggest [Traefik](https://traefik.io/) which works awesome as a reverse proxy for Docker environments.

**Comment by benjaminlyng** [comment]
Thank you for replying. My mistake was thinking port 80 was not available since I was redirected to https. :) 
It works now so thanks a lot! I took your advice and used Traefik following the guide [https://docs.traefik.io/user-guide/docker-and-lets-encrypt/](url). It didn't work initially but i found others having difficulties with the user-guide and the newest version of docker-compose. It's apparently changed it's syntax and the guide for traefik hasn't been updated.
Here's a part of my docker-compose file to show the syntax now (docker-compose version 1.17.0):

  owncloud:
    image: owncloud/server:${VERSION}
    restart: always
    expose:
      - 443
    labels:
      traefik.backend: "example.com"
      traefik.docker.network: "web"
      traefik.frontend.rule: "Host:owncloud.example.com"
      traefik.enable: "true"
      traefik.port: "80"
...
