### ISSUE TITLE
How to change "myowncloud_files"-directory on host?

### ISSUE THREAD

**Issue by freakadings** [owncloud-docker/server#82]
Hi all, 
first: i'm new to docker and owncloud.
I got everything running without any problems but now i want to change the directory of the uploaded files on my harddrive.
By default it throws everything into the docker volume on
`/var/lib/docker/volumes/myowncloud_files/_data`
but the space on my ssd i'm running docker and the host system (ubuntu 18.04 lts) is limited and i have another HDD with way more storagespace where i want the data to be stored.

Sure i could move the files from the default folder to the HDD by a script. They would be stored correctly but wouldn't appear on the owncloud web interface.

Could someone please give me a step by step discription for dummies so that the data is saved to e.g. `/mnt/mydatadrive/` ?
Is this even possible?

Thank you in advance,
Merlin

**Comment by tboerger** [comment]
I think https://stackoverflow.com/questions/40905761/how-do-i-mount-a-host-directory-as-a-volume-in-docker-compose should give you all answers. Just replace the named volume within the docker-compose.yml with a host volume as described on stackoverflow and you should be fine.

**Comment by freakadings** [comment]
Thanks for your quick reply!
I now replaced the 
`    volumes:
      - files:/mnt/data`
(about line 40) in the docker-compose.yml with
`    volumes:
      - /mnt/mydatadrive:/mnt/data
`
I ran into an error, that it will still use the old volume so after removing everything from owncloud and doing antoher 
`docker-compose up -d`
it created all folders on my other harddrive. But after that it ran into a boot-loop with the following error in its log:
`See https://doc.owncloud.org/server/10.0/go.php?to=admin-dir_permissions
Cannot write into "config" directory!
This can usually be fixed by giving the webserver write access to the config directory`

Since the harddrive i use is NTFS and chown doesn't work i added the www-data user to the "plugdev" group but still got the error above.
I tried to change the webserver user within the docker container to another which has rights to access the harddrive but since it restarts continuously i can't connect to it's shell.
The redis and db container are running without noticeable errors.

Could you please help me out again? 
Thanks a lot
Merlin

**Comment by tboerger** [comment]
Sorry, but windows is not really my topic. Maybe you can get help for that on central.owncloud.org

**Comment by freakadings** [comment]
Ok i finally got it for everyone else:
I had to change the mounting options for my ntfs drive within the /etc/fstab to:

UUID=37DA77987C79EA93 /mnt/mydatadrive ntfs quiet,defaults,permissions 0 0

now every folder and file belongs to root:root except for the Folder i mapped the owncloud data to

:)
