### ISSUE TITLE
occ not reliable

### ISSUE THREAD

**Issue by cortho** [owncloud-docker/server#84]
In our environment we perform scripted setup for ownCloud instances. Since there are no environment variables for the general email settings (see https://github.com/owncloud-docker/base#available-environment-variables) we perform this steps in a batch file with occ:

`docker exec $DOCKER_NAME occ config:system:set mail_smtpmode --value "smtp"`
`docker exec $DOCKER_NAME occ config:system:set mail_smtphost --value "smtphost"`
`docker exec $DOCKER_NAME occ config:system:set mail_smtpport --value "465"`
`docker exec $DOCKER_NAME occ config:system:set mail_from_address --value "mailfrom"`
`docker exec $DOCKER_NAME occ config:system:set mail_domain --value "maildomain"`
`docker exec $DOCKER_NAME occ config:system:set mail_smtpsecure --value "ssl"`
`docker exec $DOCKER_NAME occ config:system:set mail_smtpauth --value 1`
`docker exec $DOCKER_NAME occ config:system:set mail_smtpauthtype --value "LOGIN"`
`docker exec $DOCKER_NAME occ config:system:set mail_smtpname --value "smtp-user"`
`docker exec $DOCKER_NAME occ config:system:set mail_smtppassword --value "smtp-pass"`

Unfortunately, in almost every run occ omits at least one of those configs, even when the message says _System config value mail_smtpport set to string 465_

I could reproduce this many times and this phenomenon concerned different settings from run to run. For testing purpose I ran a script where I put a `config:system:get` after setting a value and in some cases the result was empty.

So here I face two issues:
* occ reports a config value is set, even when this is not the case
* it is obviously not possible to batch-configure ownCloud with occ

This is only a docker issue, when testing the same script with an installation w/o docker everything went fine.

**Comment by tboerger** [comment]
Just mount a shell script as a volume to /etc/post_install.d, that's how we add config customization and that works so far absolutely reliable for us. The execution from outside also works fine, I can't reproduce the mentioned behavior.

Since we are anyway only calling the occ command I can't think about anything that is related to this container.

**Comment by cortho** [comment]
Thank you, we can try this.
Still, wouldn't be the preferred way to have docker env variables for this?

**Comment by tboerger** [comment]
We are not providing all config flags as env var because not only core but any app could provide flags. Besides that it's still discussed to get rid of the current config file at all.

**Comment by cortho** [comment]
I see, thank you for the information. (Even when mail _is_ a core flag, which IMO should be supported.)

So, with your insight, I don't see what can be fixed in the docker scope, I guess the false positive occ config:system:set` message should be opened in core.

-> closing
