### ISSUE TITLE
Last docker image has broken ssl

### ISSUE THREAD

**Issue by madchap** [owncloud-docker/server#88]
Hi,

A quick feedback for now.. my watchtower container noticed that new push 5 hours ago, and updated my owncloud container (and restarted it). The container is been running fine for the past weeks.

Then, no more connection possible to the SSL port.

Image is starting well, no apparent errors, nothing in the logs per default level.
```
time="2018-10-10T15:34:14Z" level=info msg="Found new owncloud/server:latest image (sha256:28caffc18536747a19a8eb2711fac87ba0441d45b4c26585e03fb206f386480a)" 
```

That same process happened at least with no problem on these dates, with automated restart, with really nothing changing around. 

```
time="2018-09-06T12:44:15Z" level=info msg="Found new owncloud/server:latest image (sha256:b9248cbcaa287d50f43f5d2985d4ed06bbcdb2aa1241ad425027f921443ced77)" 
time="2018-09-06T13:54:09Z" level=info msg="Found new owncloud/server:latest image (sha256:9e654f9a954da9b6371b50221c4fac46721825ec45a6fd60b43d7f3c2af72e31)" 
time="2018-10-01T14:33:45Z" level=info msg="Found new owncloud/server:latest image (sha256:ed6f3a1bec5aff11a00121fe5f91d3b25429406e4d3a8ebff03272e152cd728c)" 
time="2018-10-02T09:29:19Z" level=info msg="Found new owncloud/server:latest image (sha256:5bb7da4f84df1839736f616b312864bbb1ba0bf65b31fc26f745a08f6ae3caca)" ```

**Comment by tboerger** [comment]
Sorry to hear that, but auto update on a latest tag is really a bad idea.

Please have a look at our changelog, the SSL port have been dropped in favor of a recommended reverse proxy for SSL termination.

Besides that the HTTP port changed from 80 to 8080 for getting prepared for arbitrary user ids like they are used within OpenShift.

So far this should be the only partially breaking change.

**Comment by madchap** [comment]
Hi @tboerger ,

Yes, no worries. This is more of a "test" instance than anything else ;-)

Thanks for the heads-up. I already have a reverse proxy in front, so that should be an easy fix.

Cheers!
Best,
fred
