### ISSUE TITLE
Wrong port 

### ISSUE THREAD

**Issue by esanzgar** [owncloud-docker/server#90]
I followed the instructions [here](https://doc.owncloud.org/server/10.0/admin_manual/installation/docker/) but they didn't work.

I have to change the port to 80 [here](https://github.com/owncloud-docker/server/blob/d538b1a96e57d7062703903b2c47daf91b172f8f/docker-compose.yml#L18)

**Comment by tboerger** [comment]
If you got the latest 10.0.10 the container port got to be 8080, the host port can be anything you like.
