### ISSUE TITLE
The (unset) cast is deprecated

### ISSUE THREAD

**Issue by dr1ss** [owncloud-docker/server#91]
Hello guys,
used latest version of owncloud docker to try out the entreprise edition, but owncloud.log file keep showing the following :  
{"reqId":"xxxx","level":3,"time":"2018-10-18T11:07:01+00:00","remoteAddr":"","user":"--","app":"PHP","method":"--","url":"--","message":"The (unset) cast is deprecated at \/mnt\/data\/apps\/firewall\/3rdparty\/hoa\/core\/Core.php#151"}

(It is shown every minute, so probably the cron)

**Comment by tboerger** [comment]
This is not really related to this repository, it's related to the firewall app. I will send a note to the developers.
