### ISSUE TITLE
Documentation lists https port which is not supported anymore

### ISSUE THREAD

**Issue by theScrabi** [owncloud-docker/server#94]
The [doucmentation](https://doc.owncloud.org/server/10.0/admin_manual/installation/docker/) lists a https port which does not seem to be in use anymore. It can not be processed by the docker-compose file.

**Comment by theScrabi** [comment]
Actually the whole reverseproxy setupprocedure is messing and should be documented. This is incomplete.

**Comment by tboerger** [comment]
The documentation is not managed by this repository at all, I have created an issue at https://github.com/owncloud/docs/issues/185 for you.

**Comment by tboerger** [comment]
> Actually the whole reverseproxy setupprocedure is messing and should be documented. This is incomplete.

IMHO it's not the goal to document some general reverse proxy setup, that's some pretty general task for every docker setup.

**Comment by theScrabi** [comment]
All right. Thank you :)
