### ISSUE TITLE
How to run owncloud on a different path

### ISSUE THREAD

**Issue by theScrabi** [owncloud-docker/server#95]
Hello, 

how can i run owncloud on a path different than the root path. I mean for example `mydomain.com/owncloud`.

I can set up the reverse proxy proxy `/owncloud`:
```
location /owncloud {
    proxy_pass http://localhost:8080;
}
```
But how can I tell the owncloud docker container to not redirect me to the `/` again?

**Comment by tboerger** [comment]
Besides setting up the reverse proxy you got to set the env variable OWNCLOUD_SUB_URL to /owncloud

**Comment by theScrabi** [comment]
All right thank you :)
