### ISSUE TITLE
Unable to Access via HTTPS

### ISSUE THREAD

**Issue by mneundorfer** [owncloud-docker/server#97]
The docs not only say 
> By default you can access the ownCloud instance at https://localhost/

they also provide a way on how to provide custom SSL certs. However, I seem to be unable to access OC via HTTPS (Connection refused). Also, I have not found a way to configure the HTTPS port, which also is stated in the docs 
> The container ports 80 and 443 are bound as configured in the .env file

The .env file only gives a HTTP_PORT, and setting HTTPS_PORT also has no effect for me.

Also the container does not seem to expose any port other than 8080.

Can anyone point me towards the solution here? I just don't seem to see it....

Thanks!

**Comment by mneundorfer** [comment]
Nevermind - I just found the information in the closed issues that HTTPS support has been dropped. I suggest adapting the README accordingly nevertheless

**Comment by tboerger** [comment]
There should be already a fix for the docs.

**Comment by rickyzhang82** [comment]
It took me a night to read Traefik doc to fix all Yaml spacing bugs in [the blog post](https://owncloud.org/news/docker-owncloud-traefik-reverse-proxy-lets-encrypt-ssl/). But I still can't figure it out how to enable SSL in my private network. To use Traefik, I still need to add a DNS server to provide domain name resolver. Such a hassle!

Instead, I just copy apache configuration files and SSL cert into container to enable SSL. Then, I commit that as image and run that modified image in docker-compose file.

This simple fix works for me.


`sh enable-ssl.sh [your owncloud container ID]`
```bash
docker exec -it $1 /bin/mkdir -p /etc/apache2/ssl/
docker cp resources/https.conf $1:/etc/apache2/sites-enabled/
docker cp resources/server.key $1:/etc/apache2/ssl/
docker cp resources/server.crt $1:/etc/apache2/ssl/
docker exec -it $1 /bin/chown root:root /etc/apache2/ssl/server.key
docker exec -it $1 /bin/chown root:root /etc/apache2/ssl/server.crt
docker exec -it $1 /bin/chown root:root /etc/apache2/sites-enabled/https.conf
docker exec -it $1 /usr/sbin/a2enmod ssl
```

```bash
cat resources/https.conf 
Listen 443
<VirtualHost *:443>
  ServerAdmin ${APACHE_SERVER_ADMIN}
  DocumentRoot ${APACHE_DOCUMENT_ROOT}

  ErrorLog ${APACHE_ERROR_LOG}
  CustomLog ${APACHE_ACCESS_LOG} ${APACHE_LOG_FORMAT}



  <Directory ${APACHE_DOCUMENT_ROOT}>
    AllowOverride All
    Options -Indexes +FollowSymlinks
  </Directory>
        SSLEngine on
        SSLCertificateFile /etc/apache2/ssl/server.crt
        SSLCertificateKeyFile /etc/apache2/ssl/server.key
</VirtualHost>

```

**Comment by rickyzhang82** [comment]
First of all, I'm not an Enterprise user. Neither I deploy OC to public cloud. I deployed OC in private network at home. My asus router provides Dydns domain name which allows public access from outside. I used NAT to pass through OC request from outside into OC server. Thus, I used https and exposed it from my private network. This is the most cost effective way to deploy OC at home. 

Hosting a DNS server in private network at home can't resolve my problem. I haven't found out that Traefik can do port forwarding in their front end rule. 

@mneundorfer I'd like to hear your network topology and how Traefik solve your problem. TIA

**Comment by mneundorfer** [comment]
> @mneundorfer I'd like to hear your network topology and how Traefik solve your problem. TIA

Fair enough. Also, it is quite simple: it is basically the same as yours. I deployed OC (besides various other services) in my private network at home. For those which should also be accessible from outside, I now have Traefik in place. It has certificates out-of-the-box for all services I need them for (completely transparent for me), allowing for SSL-communication when accessing them from outside my home network. Now I also don't have to open various ports on my router anymore, because all traffic from outside goes through Traefik and is then dispatched to backend services.

hth

**Comment by rickyzhang82** [comment]
@mneundorfer 

Assuming you use different URL points to your service provided by Traefik, how do you solve DNS problem? eg, public URL - owncloud.your.domain.com dispatch to your OC container, blog.your.domain.com dispatch to your wordpress and etc. Do you pay for domain and let public DNS resolve owncloud.your.domain.com and blog.your.domain.com to your public IP? You only expose Traefik port to your router?

**Comment by tboerger** [comment]
You are not forced to use Traefik, you can use whatever you want. Traefik just mades it quite easy to route traffic to docker containers.

**Comment by rickyzhang82** [comment]
@tboerger 

I understood that. But if we took away SSL by default in the default image, we need a clear path to enable SSL. I'm sure most of home use OC user will have similar trouble like me in the absence of clear instruction.

Before studying Traefik, I also tried apache2 with SSL in the physical host to reverse proxy OC container. But it failed in the OC login page. 

If my understanding of Traefik is correct, it uses different host name in HTTP/HTTPS request to route services. This requires public DNS where home user needs to pay. But I want to confirm this from you guys.

**Comment by tboerger** [comment]
Sorry, but I expect that somebody who is able to host software on his own is also able to configure a Webserver as a reverse proxy. There are hundreds or thousands of guides out there how to do that. That's not specific to owncloud.

**Comment by mneundorfer** [comment]
> @mneundorfer
> 
> Do you pay for domain and let public DNS resolve owncloud.your.domain.com and blog.your.domain.com to your public IP? You only expose Traefik port to your router?

Yes, that is exactly what happens. I do own a domain which is configured to route traffic on specific subdomains to my router. Traefik then handles the dispatching.

**Comment by max1010-sp** [comment]
> It took me a night to read Traefik doc to fix all Yaml spacing bugs in [the blog post](https://owncloud.org/news/docker-owncloud-traefik-reverse-proxy-lets-encrypt-ssl/). But I still can't figure it out how to enable SSL in my private network. To use Traefik, I still need to add a DNS server to provide domain name resolver. Such a hassle!
> 
> Instead, I just copy apache configuration files and SSL cert into container to enable SSL. Then, I commit that as image and run that modified image in docker-compose file.
> 
> This simple fix works for me.
> 
> `sh enable-ssl.sh [your owncloud container ID]`
> 
> ```shell
> cat enable-ssl.sh
> docker exec -it $1 /bin/mkdir -p /etc/apache2/ssl/
> docker cp resources/https.conf $1:/etc/apache2/sites-enabled/
> docker cp resources/server.key $1:/etc/apache2/ssl/
> docker cp resources/server.crt $1:/etc/apache2/ssl/
> docker exec -it $1 /bin/chown root:root /etc/apache2/ssl/server.key
> docker exec -it $1 /bin/chown root:root /etc/apache2/ssl/server.crt
> docker exec -it $1 /bin/chown root:root /etc/apache2/sites-enabled/https.conf
> docker exec -it $1 /usr/sbin/a2enmod ssl
> ```
> 
> ```shell
> cat resources/https.conf 
> Listen 443
> <VirtualHost *:443>
>   ServerAdmin ${APACHE_SERVER_ADMIN}
>   DocumentRoot ${APACHE_DOCUMENT_ROOT}
> 
>   ErrorLog ${APACHE_ERROR_LOG}
>   CustomLog ${APACHE_ACCESS_LOG} ${APACHE_LOG_FORMAT}
> 
> 
> 
>   <Directory ${APACHE_DOCUMENT_ROOT}>
>     AllowOverride All
>     Options -Indexes +FollowSymlinks
>   </Directory>
>         SSLEngine on
>         SSLCertificateFile /etc/apache2/ssl/server.crt
>         SSLCertificateKeyFile /etc/apache2/ssl/server.key
> </VirtualHost>
> ```

Hi bro, I like your solution, do you have an updated version for owncloud latest version?
